'use client'
import { useEffect, useState } from 'react';
import Shell from '../../components/Shell';
const def={serverName:'Extinction++ RSS',logoUrl:'/extinction-logo.png',bannerUrl:'/extinction-banner.png',primaryColor:'#b91c1c',secondaryColor:'#ef4444',buttonColor:'#b91c1c',embedColor:'#ef4444',backgroundColor:'#08111f'};
export default function Page(){ const [guilds,setGuilds]=useState([]); const [guildId,setGuildId]=useState(''); const [theme,setTheme]=useState(def); const [msg,setMsg]=useState('');
useEffect(()=>{fetch('/api/guilds').then(r=>r.json()).then(d=>{setGuilds(d||[]); if(d?.[0]?.id)setGuildId(d[0].id)})},[]);
useEffect(()=>{if(!guildId)return; fetch('/api/customization?guildId='+guildId).then(r=>r.json()).then(t=>setTheme({...def,...t}))},[guildId]);
const save=async()=>{await fetch('/api/customization',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({guildId,theme})}); setMsg('✅ Sauvegardé')};
return <Shell><h2 className="mb-6 text-4xl font-black">Personnalisation</h2><div className="grid gap-6 xl:grid-cols-2"><div className="card"><select className="input mb-4" value={guildId} onChange={e=>setGuildId(e.target.value)}>{guilds.map(g=><option key={g.id} value={g.id}>{g.name||g.id}</option>)}</select><input className="input mb-4" value={theme.serverName} onChange={e=>setTheme({...theme,serverName:e.target.value})} placeholder="Nom"/><input className="input mb-4" value={theme.logoUrl} onChange={e=>setTheme({...theme,logoUrl:e.target.value})} placeholder="URL Logo"/><input className="input mb-4" value={theme.bannerUrl} onChange={e=>setTheme({...theme,bannerUrl:e.target.value})} placeholder="URL Bannière"/><div className="grid grid-cols-2 gap-4"><input type="color" value={theme.primaryColor} onChange={e=>setTheme({...theme,primaryColor:e.target.value})}/><input type="color" value={theme.secondaryColor} onChange={e=>setTheme({...theme,secondaryColor:e.target.value})}/><input type="color" value={theme.buttonColor} onChange={e=>setTheme({...theme,buttonColor:e.target.value})}/><input type="color" value={theme.embedColor} onChange={e=>setTheme({...theme,embedColor:e.target.value})}/></div><button className="btn btn-primary mt-6" onClick={save}>Sauvegarder</button><p>{msg}</p></div><div className="card">{theme.bannerUrl&&<img src={theme.bannerUrl} className="mb-4 h-40 w-full rounded-3xl object-cover"/>}<div className="flex items-center gap-4">{theme.logoUrl?<img src={theme.logoUrl} className="h-20 w-20 rounded-2xl object-cover"/>:<div className="grid h-20 w-20 place-items-center rounded-2xl text-3xl font-black" style={{background:theme.primaryColor}}>E</div>}<div><h3 className="text-3xl font-black">{theme.serverName}</h3><p style={{color:theme.secondaryColor}}>Aperçu thème</p></div></div></div></div></Shell> }
