const battlepass=require('./battlepass.cjs');
const crypto=require('crypto');
function account(db,guildId,userId){if(!/^\d{15,22}$/.test(userId||''))throw new Error('ID Discord du joueur invalide.');db.bank||={accounts:[]};db.bank.accounts||=[];let a=db.bank.accounts.find(a=>a.guildId===guildId&&a.userId===userId);if(!a){a={guildId,userId,bank:0,cash:0};db.bank.accounts.push(a);}return a;}
function credit(db,guildId,userId,amount,reason){if(!Number.isSafeInteger(amount)||amount<0)throw new Error('Montant invalide.');const a=account(db,guildId,userId);if(!Number.isSafeInteger((a.bank||0)+amount))throw new Error('Solde trop élevé.');a.bank=(a.bank||0)+amount;db.economy||={transactions:[]};(db.economy.transactions||=[]).push({id:crypto.randomUUID(),guildId,userId,amount,reason,createdAt:new Date().toISOString()});return a;}
function reviewProof(db,guildId,proofId,decision,actorId,now=Date.now()){const proof=(db.questProofs||[]).find(p=>p.id===proofId&&p.guildId===guildId);if(!proof)throw new Error('Preuve introuvable.');if(proof.status!=='pending')throw new Error('Cette preuve a déjà été traitée.');if(!['approve','reject'].includes(decision))throw new Error('Décision invalide.');const quest=(db.quests||[]).find(q=>q.id===proof.questId&&q.guildId===guildId);if(!quest)throw new Error('Quête introuvable.');if(decision==='approve'){
  const quests=require('./quests.cjs');if(quest.enabled===false)throw new Error('Quête désactivée.');proof.periodKey||=quests.period(quest,Date.parse(proof.createdAt));
  if(quests.awarded(db,guildId,proof.userId,quest,proof.periodKey))throw new Error('Récompense déjà attribuée pour cette période de quête.');const server=quest.serverId?[...(db.guilds?.[guildId]?.servers||[]),...(db.connectedServers||[])].find(s=>(!s.guildId||s.guildId===guildId)&&[s.id,s.name].includes(quest.serverId)):null;proof.game||=server?.game||quest.game;proof.serverId||=server?.id||quest.serverId;
  credit(db,guildId,proof.userId,quest.reward||0,`Quête ${quest.title}`);db.guilds||={};db.guilds[guildId]||={id:guildId};db.guilds[guildId].progress||={};const progress=db.guilds[guildId].progress[proof.userId]||={xp:0,claimed:[]};battlepass.earn(db,guildId,proof.userId,quest.xp||0,proof,credit,now);
}proof.status=decision==='approve'?'approved':'rejected';proof.reviewedBy=actorId;proof.reviewedAt=new Date().toISOString();return proof;}
module.exports={account,credit,reviewProof};
