const crypto=require('crypto');
function account(db,guildId,userId){if(!/^\d{15,22}$/.test(userId||''))throw new Error('ID Discord du joueur invalide.');db.bank||={accounts:[]};db.bank.accounts||=[];let a=db.bank.accounts.find(a=>a.guildId===guildId&&a.userId===userId);if(!a){a={guildId,userId,bank:0,cash:0};db.bank.accounts.push(a);}return a;}
function credit(db,guildId,userId,amount,reason){if(!Number.isSafeInteger(amount)||amount<0)throw new Error('Montant invalide.');const a=account(db,guildId,userId);if(!Number.isSafeInteger((a.bank||0)+amount))throw new Error('Solde trop élevé.');a.bank=(a.bank||0)+amount;db.economy||={transactions:[]};(db.economy.transactions||=[]).push({id:crypto.randomUUID(),guildId,userId,amount,reason,createdAt:new Date().toISOString()});return a;}
function reviewProof(db,guildId,proofId,decision,actorId){const proof=(db.questProofs||[]).find(p=>p.id===proofId&&p.guildId===guildId);if(!proof)throw new Error('Preuve introuvable.');if(proof.status!=='pending')throw new Error('Cette preuve a déjà été traitée.');if(!['approve','reject'].includes(decision))throw new Error('Décision invalide.');const quest=(db.quests||[]).find(q=>q.id===proof.questId&&q.guildId===guildId);if(!quest)throw new Error('Quête introuvable.');if(decision==='approve'){
  // One reward per quest and player; separate recurring quests need separate instances.
  if((db.questProofs||[]).some(p=>p.id!==proof.id&&p.guildId===guildId&&p.userId===proof.userId&&p.questId===proof.questId&&p.status==='approved'))throw new Error('Récompense déjà attribuée pour cette quête.');
  credit(db,guildId,proof.userId,quest.reward||0,`Quête ${quest.title}`);db.guilds[guildId]||={id:guildId};db.guilds[guildId].progress||={};const progress=db.guilds[guildId].progress[proof.userId]||={xp:0,claimed:[]};if(!Number.isSafeInteger(quest.xp||0)||quest.xp<0)throw new Error('XP invalide.');progress.xp+=(quest.xp||0);
  for(const level of db.battlepass?.levels||db.battlepasses?.[guildId]?.levels||[]){if(!level.premium&&progress.xp>=level.xp&&!(progress.claimed||=[]).includes(level.id)){credit(db,guildId,proof.userId,level.reward||0,`Battle Pass ${level.level}`);progress.claimed.push(level.id);}}
}proof.status=decision==='approve'?'approved':'rejected';proof.reviewedBy=actorId;proof.reviewedAt=new Date().toISOString();return proof;}
module.exports={account,credit,reviewProof};
