const crypto=require('node:crypto');
const secure=require('./secure-store.cjs');
const games=require('./games.cjs');
const clients=new Map();
function configured(s,provider){return provider==='cftools'?!!(s.cfServerId&&s.cfApplicationId&&s.cfSecret):provider==='battlemetrics'?!!s.bmServerId:false;}
function validate(s){for(const k of ['cfServerId','cfApplicationId','cfBanlistId'])if(s[k]&&!/^[A-Za-z0-9_-]{1,100}$/.test(s[k]))throw new Error('Identifiant CFTools invalide.');if(s.bmServerId&&!/^\d{1,20}$/.test(s.bmServerId))throw new Error('Identifiant BattleMetrics numérique requis.');if((s.cfServerId||s.cfDeliveryEnabled)&&games.normalize(s.game,s.platform)!=='dayz_pc')throw new Error('Le connecteur CFTools intégré concerne DayZ PC.');if(s.externalMonitor&&!['cftools','battlemetrics'].includes(s.externalMonitor))throw new Error('Source de surveillance externe invalide.');if(s.externalMonitor&&!configured(s,s.externalMonitor))throw new Error('Configure le connecteur de surveillance choisi.');}
function cfClient(s){validate(s);if(!configured(s,'cftools'))throw new Error('ID serveur, ID application et secret CFTools requis.');const key=crypto.createHash('sha256').update(JSON.stringify([s.guildId,s.id,s.cfServerId,s.cfApplicationId,s.cfSecret])).digest('hex');const cached=clients.get(key);if(cached&&cached.until>Date.now())return cached.client;
 const sdk=require('cftools-sdk'),{GotHttpClient}=require('cftools-sdk/lib/internal/http');
 const client=new sdk.CFToolsClientBuilder().withServerApiId(s.cfServerId).withCredentials(s.cfApplicationId,secure.decrypt(s.cfSecret)).withHttpClient(auth=>{auth.reportExpired();return new GotHttpClient(sdk.httpClient(false,{enableDebugLogging:false,logBody:false,userAgent:'ExtinctionRSS/7'}).extend({timeout:{request:15000},retry:{limit:0},followRedirect:false}),auth);}).build();
 if(clients.size>=100)clients.delete(clients.keys().next().value);clients.set(key,{client,until:Date.now()+300000});return client;
}
function plainId(id){return String(id?.id||id||'');}
function uid(value){if(typeof value!=='string')throw new Error('Identifiant joueur requis.');const sdk=require('cftools-sdk');if(/^\d{17}$/.test(value))return sdk.SteamId64.of(value);if(/^[A-Za-z0-9_+\/-]{43}=$/.test(value))return sdk.BohemiaInteractiveId.of(value);throw new Error('SteamID64 ou UID DayZ de 44 caractères requis.');}
async function cfRead(s,action='status',playerUid,deps={}){const c=deps.client||cfClient(s);if(action==='status'){const info=await c.getServerInfo({}),sessions=await c.listGameSessions({});return {source:'cftools',status:'api_reachable',name:info.nickname,players:sessions.length,checkedAt:new Date().toISOString(),sessions:sessions.slice(0,500).map(p=>({id:p.id,name:p.playerName,steamId:plainId(p.steamId),cftoolsId:plainId(p.cftoolsId),loaded:p.live?.loaded===true,ping:p.live?.ping?.actual,position:p.live?.position?.latest?{x:p.live.position.latest.x,z:p.live.position.latest.y}:undefined}))};}
 if(action==='player'){const p=await c.getPlayerDetails(uid(playerUid));return {source:'cftools',names:p.names,steamId:plainId(p.identities?.steam),dayzUid:plainId(p.identities?.bohemia),playtime:p.playtime,sessions:p.sessions,firstSeen:p.firstSeen,lastSeen:p.lastSeen,statistics:p.statistics?.dayz};}
 if(action==='bans'){if(!s.cfBanlistId)throw new Error('Identifiant de banlist CFTools requis.');return {source:'cftools',bans:await c.listBans({playerId:uid(playerUid),list:require('cftools-sdk').Banlist.of(s.cfBanlistId)})};}
 throw new Error('Lecture CFTools inconnue.');}
function action(body){if(!['ban','whitelist','priority'].includes(body.action))throw new Error('Action CFTools invalide.');uid(body.playerUid);if(typeof body.reason!=='string'||!body.reason.trim()||body.reason.length>500)throw new Error('Motif de 1 à 500 caractères requis.');if(body.expiresAt&&(!/^\d{4}-\d\d-\d\dT.*(Z|[+-]\d\d:\d\d)$/.test(body.expiresAt)||!Number.isFinite(Date.parse(body.expiresAt))||Date.parse(body.expiresAt)<=Date.now()))throw new Error('Expiration ISO future avec fuseau requise.');return {action:body.action,playerUid:body.playerUid,reason:body.reason.trim(),expiresAt:body.expiresAt||null};}
async function cfExecute(s,body,deps={}){const a=action(body),c=deps.client||cfClient(s),playerId=uid(a.playerUid),expiration=a.expiresAt?new Date(a.expiresAt):'Permanent';if(a.action==='ban'){if(!s.cfBanlistId)throw new Error('Banlist CFTools requise.');await c.putBan({playerId,list:require('cftools-sdk').Banlist.of(s.cfBanlistId),reason:a.reason,expiration});}else{const id=await c.resolve(playerId);await c[a.action==='whitelist'?'putWhitelist':'putPriorityQueue']({id,comment:a.reason,expires:expiration});}return 'Demande acceptée par CFTools. Vérifie son application dans le serveur.';}
async function cfDelivery(s,identity,item,deps={}){if(!s.cfDeliveryEnabled||games.normalize(s.game,s.platform)!=='dayz_pc')throw new Error('Livraison GameLabs non activée pour ce serveur DayZ PC.');const c=deps.client||cfClient(s);const id=await c.resolve(uid(identity.uid));const sessions=await c.listGameSessions({});const session=sessions.find(p=>plainId(p.cftoolsId)===plainId(id)&&p.live?.loaded);if(!session)throw new Error('Le joueur doit être connecté et chargé dans DayZ.');const contents=require('./shop-items.cjs').items(item);if(contents.some(v=>!/^[A-Za-z0-9_]{1,100}$/.test(v.className)))throw new Error('Classe DayZ invalide.');return {execute:async()=>{for(const v of contents)await c.spawnItem({session,itemClass:v.className,quantity:v.quantity,debug:false,stacked:false});}};}
async function bmRead(s,action='status',deps={}){validate(s);if(!configured(s,'battlemetrics'))throw new Error('ID serveur BattleMetrics requis.');if(!['status','sessions'].includes(action))throw new Error('Lecture BattleMetrics inconnue.');if(action==='sessions'&&!s.bmToken)throw new Error('Jeton BattleMetrics avec accès aux sessions requis.');const endpoint=`https://api.battlemetrics.com/servers/${s.bmServerId}${action==='sessions'?'/relationships/sessions?page[size]=25':'?include=player'}`;const headers={Accept:'application/vnd.api+json'};if(s.bmToken)headers.Authorization=`Bearer ${secure.decrypt(s.bmToken)}`;
 const r=await(deps.fetch||fetch)(endpoint,{headers,redirect:'error',signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`BattleMetrics a refusé la requête (${r.status}).`);if(Number(r.headers?.get('content-length'))>2000000)throw new Error('Réponse BattleMetrics trop volumineuse.');let raw;if(r.body?.getReader){const reader=r.body.getReader(),parts=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>2000000){await reader.cancel();throw new Error('Réponse BattleMetrics trop volumineuse.');}parts.push(Buffer.from(value));}raw=Buffer.concat(parts).toString('utf8');}else raw=await r.text();if(Buffer.byteLength(raw)>2000000)throw new Error('Réponse BattleMetrics trop volumineuse.');const data=JSON.parse(raw);
 if(action==='sessions')return {source:'battlemetrics',sessions:(Array.isArray(data.data)?data.data:[]).slice(0,25).map(p=>({id:p.id,start:p.attributes?.start,stop:p.attributes?.stop,playerId:p.relationships?.player?.data?.id})),checkedAt:new Date().toISOString()};
 if(data.data?.type!=='server'||String(data.data.id)!==s.bmServerId)throw new Error('Réponse BattleMetrics incompatible avec le serveur choisi.');const a=data.data.attributes||{};return {source:'battlemetrics',status:a.status||'unknown',name:a.name,players:a.players,slots:a.maxPlayers,checkedAt:new Date().toISOString(),sessions:(data.included||[]).filter(p=>p.type==='player').slice(0,500).map(p=>({id:p.id,name:p.attributes?.name}))};}
async function status(s,deps={}){return s.externalMonitor==='cftools'?cfRead(s,'status',undefined,deps):s.externalMonitor==='battlemetrics'?bmRead(s,'status',deps):Promise.reject(new Error('Source externe non choisie.'));}
module.exports={configured,validate,cfRead,cfExecute,cfDelivery,bmRead,status,action,plainId};
