const crypto=require('node:crypto');
const live=require('./live-events.cjs');
function sign(secret,timestamp,body){return crypto.createHmac('sha256',secret).update(`${timestamp}\n${body}`).digest('hex');}
function verify(secret,timestamp,body,signature,now=Date.now()){if(!/^\d{13}$/.test(timestamp||'')||Math.abs(now-Number(timestamp))>300000||!/^[a-f0-9]{64}$/.test(signature||''))return false;return crypto.timingSafeEqual(Buffer.from(sign(secret,timestamp,body),'hex'),Buffer.from(signature,'hex'));}
function text(v,max=100){if(typeof v!=='string'||!v||v.length>max||/[\r\n\0]/.test(v))throw new Error('Texte du jeu invalide.');return v;}
function event(value){if(!value||!['kill','death','suicide','connect','disconnect','position','chat'].includes(value.type)||!Array.isArray(value.actors)||value.actors.length<1||value.actors.length>2)throw new Error('Événement du jeu invalide.');const actors=value.actors.map(a=>{const p={uid:text(a.uid),name:text(a.name)};if(a.x!==undefined||a.z!==undefined){if(![a.x,a.z].every(n=>Number.isFinite(n)&&Math.abs(n)<1000000000))throw new Error('Position du joueur invalide.');p.x=a.x;p.z=a.z;}return p;});const id=text(value.id,128),type=value.type;if(type==='kill'&&actors.length!==2)throw new Error('Victime et tueur requis pour un kill.');return {id:live.digest(`bridge:${id}`),event:{type,source:'game_bridge',actors,player:actors[0].name,playerUid:actors[0].uid,...type==='kill'?{victim:actors[0].name,killer:actors[1].name,killerUid:actors[1].uid,weapon:value.weapon?text(value.weapon):'',distance:Number.isFinite(value.distance)&&value.distance>=0?value.distance:undefined}:{},...type==='chat'?{message:text(value.message,500)}:{}}};}
function ingest(db,s,body,now=new Date().toISOString()){if(!Array.isArray(body.events)||body.events.length>100)throw new Error('100 événements maximum.');const entries=body.events.map(event).map(e=>({...e,id:live.digest(`${s.guildId}:${s.id}:${e.id}`)}));const count=live.apply(db,s,entries,now);return {count,state:{checkedAt:now,status:'connected',capabilities:{delivery:body.capabilities?.delivery===true},eventsRead:(s.bridgeState?.eventsRead||0)+count}};}
function claim(db,s){const row=(db.deliveries||[]).find(d=>d.guildId===s.guildId&&d.serverId===s.id&&d.status==='bridge_queued');if(!row)return null;row.status='bridge_claimed';row.claimedAt=new Date().toISOString();const purchase=db.shopPurchases?.find(p=>p.id===row.id&&p.guildId===s.guildId);if(purchase)purchase.status=row.status;return {id:row.id,playerUid:row.playerUid,className:row.className,quantity:row.quantity,x:row.x,z:row.z};}
function acknowledge(db,s,body){const row=db.deliveries?.find(d=>d.id===body.deliveryId&&d.guildId===s.guildId&&d.serverId===s.id);if(!row||!['bridge_claimed','delivered','delivery_uncertain'].includes(row.status))throw new Error('Livraison introuvable ou non réclamée.');if(row.status==='delivered')return;if(!['delivered','delivery_uncertain'].includes(body.status))throw new Error('Résultat de livraison invalide.');row.status=body.status;row.completedAt=new Date().toISOString();row.result=String(body.result||'').slice(0,500);const p=db.shopPurchases?.find(p=>p.id===row.id&&p.guildId===s.guildId);if(p){p.status=row.status;p.completedAt=row.completedAt;}}
module.exports={sign,verify,event,ingest,claim,acknowledge};
