// Suggestions only. Terrain images, availability and coordinate calibration are not inferred.
const names={
  dayz:['Chernarus','Livonia','Sakhal','Nasdara / Badlands','Namalsk','Deer Isle','Banov','Esseker','Takistan','Chiemsee','Iztek','Melkart','Pripyat','Valning','Lux','Alteria'],
  ark:["Aberration", "Althemia Magic Ground", "Amissa", "Appalachia", "Arkis", "Arkopolis Free", "ASurviveTheNight (Survive the Night)", "Astraeos", "Atlantis", "Bjarnheim", "Club ARK", "Crystal Isles", "Dark Abyss Dome", "Dark’s Event Map", "Dragon Topía", "Dragon Triangle", "Eden Premium", "EliteArk Arena", "EliteArk: Deadzone", "Enclave: Survival Skyward", "Epiphany", "Extinction", "ExtinctionOverGrowth", "FLASH WARZONE", "Fjordur", "Forglar — Part I", "Forglar — Part II", "Genesis: Part 1 (Genesis Ascended)", "Genesis: Part 2", "Gigark Islands", "Ark Ice Age", "IMSARK Hood", "Insaluna (Insulana)", "Lost City (LostCity_WP)", "Lost Colony", "Lost Island", "MR_Map2", "Nova Arena Map", "Nyrandil", "PRIMATEPIX", "Prometeus: Frontiers of Ark", "Ragnarok (Ragnarok Ascended)", "Ragnarok Reborn Reforged", "Reverence", "Rogue Nexus", "Rustfall", "Schneeti’s Team Deathmatch", "Scorched Earth", "Scorched Earth Reborn", "Svartalfheim — Gratuit", "Svartalfheim Premium", "TaeniaStella", "Temptress Lagoon — Gratuit", "Temptress Lagoon Premium", "Thaloria", "The Center", "The Chill Hub (ASA n Chill)", "The Island", "The Island Reforged", "The Volcano", "TLT Deadzone", "Valguero (Valguero Ascended)", "Vintal", "VRO Dungeon Plus", "WAK CITY", "Ragnarok", "Valguero", "Genesis Part 1", "Genesis Part 2", "Svartalfheim", "Forglar", "Temptress Lagoon", "Caballus"],
  arma:["Afghanistan", "African Everon", "Anizay", "Arland", "Bozcaada", "Burgamo", "Chernarus Remake WIP", "Elvran", "Elvran SNOW", "Everon", "Fallujah", "Favela RIO", "FUBAR LAND", "G Coast Islands", "Gm_flatgrass_maps", "Iraq 1990", "Kadykchan (PTH_Kadykchan)", "Kolguyev", "Kunar Province — Conflict Remake", "Kunar Province — FOB Michigan", "Metro Ascension", "Nizla Island PVE", "Old San Juan Puerto Rico", "Ramadi", "Ramadi Remastered", "Ruha 101st", "Shandilar", "Simonra Woodoo", "Smoltey Island — 1940s", "Soledar GM", "Vietnam", "Zarichne", "Zimnitrita", "Zimnitrita Castle Orion", "Al Shabur", "Luna", "Operation Uppercut", "Cain"],
  conan:['Exiled Lands','Isle of Siptah','Savage Wilds'],
  palworld:['Palpagos','Sakurajima','Feybreak'],
  '7dtd':['Navezgane','Pregen','Monde généré aléatoirement'],
  aniimo:[]
};
function suggestions(game,servers=[],maps=[]){const key=game?.startsWith('dayz')?'dayz':game;return [...new Set([...(names[key]||[]),...servers.filter(s=>s.game===game).map(s=>s.map),...maps.filter(m=>m.game===game).map(m=>m.name)].filter(Boolean))];}
module.exports={suggestions};
