const crypto=require('node:crypto');
const appStore=require('./app-store.cjs');
let initialized;
const hash=s=>crypto.createHash('sha256').update(String(s)).digest('hex');
function member(network,guildId){if(!network.members.includes(guildId))throw new Error('Ce Discord n’a pas rejoint ce réseau.');}
function view(network,guildId){member(network,guildId);const {inviteHash,...result}=network;return result;}
function create(name,guildId){if(typeof name!=='string'||!name.trim()||name.length>100)throw new Error('Nom de réseau requis (100 caractères maximum).');const code=crypto.randomBytes(24).toString('hex');return {code,network:{id:crypto.randomUUID(),name:name.trim(),ownerGuildId:guildId,members:[guildId],reports:[],inviteHash:hash(code),inviteExpiresAt:new Date(Date.now()+7*86400000).toISOString(),createdAt:new Date().toISOString()}};}
function publish(network,guildId,body){member(network,guildId);if(!['dayz_pc','dayz_ps','dayz_xbox','ark','arma','palworld','conan','7dtd'].includes(body.game)||typeof body.playerUid!=='string'||!body.playerUid||body.playerUid.length>100||/[\r\n\0]/.test(body.playerUid)||typeof body.reason!=='string'||!body.reason.trim()||body.reason.length>2000)throw new Error('Jeu, UID et motif documenté requis.');if(body.evidence){const u=new URL(body.evidence);if(u.protocol!=='https:'||u.username||u.password)throw new Error('Lien HTTPS de preuve requis.');}if(network.reports.length>=5000)throw new Error('Limite de 5000 signalements atteinte.');const report={id:crypto.randomUUID(),sourceGuildId:guildId,game:body.game,playerUid:body.playerUid,playerName:String(body.playerName||body.playerUid).slice(0,100),reason:body.reason,evidence:String(body.evidence||'').slice(0,2000),status:'published',createdAt:new Date().toISOString()};network.reports.push(report);return report;}
function withdraw(network,gid,reportId){member(network,gid);const r=network.reports.find(r=>r.id===reportId);if(!r||r.sourceGuildId!==gid&&network.ownerGuildId!==gid)throw new Error('Seul l’auteur ou le propriétaire du réseau peut retirer ce signalement.');r.status='withdrawn';r.withdrawnAt=new Date().toISOString();return r;}
async function ready(){const p=await appStore.ready();if(!initialized)initialized=p.query('CREATE TABLE IF NOT EXISTS extinction_moderation_networks (id TEXT PRIMARY KEY, data JSONB NOT NULL)').catch(e=>{initialized=null;throw e;});await initialized;return p;}
async function list(gid){return(await(await ready()).query("SELECT data FROM extinction_moderation_networks WHERE data->'members' ? $1",[gid])).rows.map(r=>view(r.data,gid));}
async function insert(name,gid){const result=create(name,gid);await(await ready()).query('INSERT INTO extinction_moderation_networks(id,data) VALUES($1,$2)',[result.network.id,JSON.stringify(result.network)]);return {network:view(result.network,gid),code:result.code};}
async function update(id,gid,action,body){const c=await(await ready()).connect();try{await c.query('BEGIN');const result=(await c.query('SELECT data FROM extinction_moderation_networks WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!result)throw new Error('Réseau introuvable.');const n=result.data;member(n,gid);let response;
 if(action==='publish')response=publish(n,gid,body);
 else if(action==='withdraw')response=withdraw(n,gid,body.reportId);
 else if(action==='leave'){if(n.ownerGuildId===gid)throw new Error('Le propriétaire du réseau ne peut pas le quitter.');n.members=n.members.filter(v=>v!==gid);response={left:true};}
 else if(action==='invite'){if(n.ownerGuildId!==gid)throw new Error('Le propriétaire du réseau renouvelle les invitations.');const code=crypto.randomBytes(24).toString('hex');n.inviteHash=hash(code);n.inviteExpiresAt=new Date(Date.now()+7*86400000).toISOString();response={code};}
 else throw new Error('Action inconnue.');await c.query('UPDATE extinction_moderation_networks SET data=$2 WHERE id=$1',[id,JSON.stringify(n)]);await c.query('COMMIT');return response;
 }catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
async function join(code,gid){if(!/^[a-f0-9]{48}$/.test(code||''))throw new Error('Invitation invalide.');const c=await(await ready()).connect();try{await c.query('BEGIN');const result=(await c.query("SELECT data FROM extinction_moderation_networks WHERE data->>'inviteHash'=$1 FOR UPDATE",[hash(code)])).rows[0];if(!result||Date.parse(result.data.inviteExpiresAt)<=Date.now())throw new Error('Invitation expirée ou révoquée.');const n=result.data;if(!n.members.includes(gid)){if(n.members.length>=100)throw new Error('Réseau complet (100 Discords).');n.members.push(gid);}await c.query('UPDATE extinction_moderation_networks SET data=$2 WHERE id=$1',[n.id,JSON.stringify(n)]);await c.query('COMMIT');return view(n,gid);}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e;}finally{c.release();}}
module.exports={hash,member,view,create,publish,withdraw,list,insert,update,join};
