const secure=require('./secure-store.cjs');
const hosting=require('./hosting.cjs');
function configured(s){return s.apiType==='pterodactyl'?!!(s.panelUrl&&s.panelServerId&&s.panelApiKey):hosting.isNitrado(s)&&!!(s.nitradoServiceId||s.nitradoId);}
function validate(s){if(s.apiType&&!['pterodactyl','nitrado'].includes(s.apiType))throw new Error('Connecteur API invalide.');if(s.apiType==='nitrado'&&!hosting.isNitrado(s))throw new Error('Le connecteur Nitrado exige un serveur Nitrado.');if(s.panelServerId&&!/^[A-Za-z0-9-]{1,64}$/.test(s.panelServerId))throw new Error('Identifiant serveur Pterodactyl invalide.');if(s.apiType==='pterodactyl'&&(!hosting.panelUrl(s)||!s.panelServerId))throw new Error('URL HTTPS du panel et identifiant serveur Pterodactyl requis.');}
async function request(db,s,operation,action,fetcher=fetch){validate(s);let url,headers,body;
 if(s.apiType==='pterodactyl'){if(!configured(s))throw new Error('Clé API Client du panel requise.');url=new URL(`/api/client/servers/${s.panelServerId}/${operation==='status'?'resources':'power'}`,s.panelUrl).href;headers={Authorization:`Bearer ${secure.decrypt(s.panelApiKey)}`,Accept:'application/vnd.pterodactyl.v1+json','Content-Type':'application/json'};if(operation==='power')body={signal:action};}
 else{if(!hosting.isNitrado(s))throw new Error('API de cet hébergeur non configurée.');const token=secure.getGuildToken(db,s.guildId);if(!token)throw new Error('Compte Nitrado de ce Discord non connecté.');const service=s.nitradoId||s.nitradoServiceId;if(!/^\d+$/.test(service||''))throw new Error('ID Nitrado requis.');url=`https://api.nitrado.net/services/${service}/gameservers${operation==='power'?'/'+action:''}`;headers={Authorization:`Bearer ${token}`,Accept:'application/json','Content-Type':'application/json'};}
 const result=await fetcher(url,{method:operation==='power'?'POST':'GET',headers,body:body?JSON.stringify(body):undefined,redirect:'error',signal:AbortSignal.timeout(15000)});if(!result.ok)throw new Error(`Le panel a refusé la requête (${result.status}).`);if(operation==='power')return {accepted:true};const data=await result.json();if(s.apiType==='pterodactyl'){const a=data.attributes||{};return {status:a.current_state||'unknown',cpu:a.resources?.cpu_absolute,memoryBytes:a.resources?.memory_bytes,source:'pterodactyl'};}const g=data.data?.gameserver||{};return {status:g.status||'unknown',players:g.query?.player_current,slots:g.query?.player_max,source:'nitrado'};
}
function power(db,s,action,fetcher){if(!['start','stop','restart'].includes(action))throw new Error('Action serveur invalide.');return request(db,s,'power',action,fetcher);}
const status=(db,s,fetcher)=>request(db,s,'status',undefined,fetcher);
module.exports={configured,validate,power,status};
