const crypto=require('node:crypto');
const games=require('./games.cjs');
function period(q,now=Date.now()){const d=new Date(now);if(q.type==='daily')return d.toISOString().slice(0,10);if(q.type==='weekly'){const day=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-day);return d.toISOString().slice(0,10);}return 'once';}
function matches(q,s){return (!q.serverId||[s.id,s.name].includes(q.serverId))&&(!q.game||games.normalize(q.game)===games.normalize(s.game,s.platform));}
function validate(q){if(!q.title?.trim())throw new Error('Titre de quête requis.');if(!['once','daily','weekly'].includes(q.type||'once'))throw new Error('Fréquence : once, daily ou weekly.');if(!['manual','kill','connect','death','suicide','chat'].includes(q.eventType||'manual'))throw new Error('Événement de quête invalide.');for(const k of ['reward','xp','target'])if(q[k]!==undefined&&(!Number.isSafeInteger(q[k])||q[k]<0||q[k]>100000000))throw new Error(`${k} invalide.`);if(q.eventType&&q.eventType!=='manual'&&!(q.target>0))throw new Error('Objectif de progression supérieur à zéro requis.');return q;}
function awarded(db,gid,user,q,key){return(db.questProofs||[]).some(p=>p.guildId===gid&&p.userId===user&&p.questId===q.id&&p.status==='approved'&&(p.periodKey||'once')===key);}
function processEvent(db,s,e,now){const ops=require('./game-operations.cjs'),economy=require('./economy.cjs');const identity=ops.linked(db,s.guildId,s.id,e.type==='kill'?e.killerUid:e.playerUid);if(!identity)return;const user=identity.userId;
 if(e.type==='kill'){if(!e.killerUid||e.killerUid===e.playerUid)return;const victim=ops.linked(db,s.guildId,s.id,e.playerUid);const f=ops.faction(db,s.guildId,s.id,user);if(victim?.userId===user||(f&&victim&&f.members.includes(victim.userId)))return;}
 for(const q of db.quests||[]){if(q.guildId!==s.guildId||q.enabled===false||q.eventType!==e.type||!matches(q,s))continue;const key=period(q,Date.parse(now));if(awarded(db,s.guildId,user,q,key))continue;db.questProgress||=[];let p=db.questProgress.find(p=>p.guildId===s.guildId&&p.userId===user&&p.questId===q.id&&p.periodKey===key);if(!p){p={id:crypto.randomUUID(),guildId:s.guildId,userId:user,questId:q.id,periodKey:key,count:0};db.questProgress.push(p);}if(p.lastEventId===e.id)continue;p.lastEventId=e.id;p.count++;p.updatedAt=now;if(p.count>=(q.target||1)){const proof={id:crypto.randomUUID(),guildId:s.guildId,userId:user,questId:q.id,serverId:s.id,game:s.game,periodKey:key,eventId:e.id,status:'pending',createdAt:now};(db.questProofs||=[]).push(proof);economy.reviewProof(db,s.guildId,proof.id,'approve','game_events',Date.parse(now));}}
}
module.exports={period,matches,validate,awarded,processEvent};
