const store=require('./app-store.cjs');
let init;
function validateUrl(value){if(!value)return;if(typeof value!=='string'||value.length>2000)throw new Error('Lien image invalide.');if(/^\/api\/server-image\?serverId=[A-Za-z0-9_-]{1,100}$/.test(value))return;let u;try{u=new URL(value);}catch{throw new Error('Lien HTTPS vers une image requis.');}if(u.protocol!=='https:'||u.username||u.password)throw new Error('Lien HTTPS sans identifiants requis pour l’image.');}
function decode(value){if(typeof value!=='string'||value.length>800000||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/]+=*$/.test(value))throw new Error('Image PNG, JPEG ou WebP de 600 Ko maximum requise.');const data=Buffer.from(value.split(',')[1],'base64');if(data.length>600000||data.length<24)throw new Error('Image trop volumineuse ou invalide.');let type,width,height;
 if(data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))&&data.toString('ascii',12,16)==='IHDR'){type='image/png';width=data.readUInt32BE(16);height=data.readUInt32BE(20);}
 else if(data[0]===255&&data[1]===216){type='image/jpeg';let pos=2;while(pos+4<data.length){if(data[pos++]!==255)throw new Error('JPEG invalide.');while(data[pos]===255)pos++;const marker=data[pos++];if(marker===217||marker===218)break;if(marker===216||marker===1||(marker>=208&&marker<=215))continue;const length=data.readUInt16BE(pos);if(length<2||pos+length>data.length)throw new Error('JPEG invalide.');if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(marker)){height=data.readUInt16BE(pos+3);width=data.readUInt16BE(pos+5);break;}pos+=length;}}
 else if(data.toString('ascii',0,4)==='RIFF'&&data.toString('ascii',8,12)==='WEBP'){type='image/webp';const format=data.toString('ascii',12,16);if(format==='VP8X'&&data.length>=30){width=1+data.readUIntLE(24,3);height=1+data.readUIntLE(27,3);}else if(format==='VP8 '&&data.length>=30&&data.subarray(23,26).equals(Buffer.from([157,1,42]))){width=data.readUInt16LE(26)&16383;height=data.readUInt16LE(28)&16383;}else if(format==='VP8L'&&data[20]===47&&data.length>=25){const bits=data.readUInt32LE(21);width=1+(bits&16383);height=1+((bits>>>14)&16383);}}
 if(!type||!width||!height||width>2048||height>2048||width*height>4194304)throw new Error('Image valide de 2048 × 2048 pixels maximum requise.');return {data,type,width,height};}
async function ready(){const p=await store.ready();if(!init)init=p.query('CREATE TABLE IF NOT EXISTS extinction_server_images (guild_id TEXT NOT NULL,server_id TEXT NOT NULL,mime_type TEXT NOT NULL,image BYTEA NOT NULL,updated_at TIMESTAMPTZ DEFAULT NOW(),PRIMARY KEY(guild_id,server_id))').catch(e=>{init=null;throw e});await init;return p;}
async function save(gid,sid,image){const {data,type}=decode(image);await(await ready()).query('INSERT INTO extinction_server_images(guild_id,server_id,mime_type,image) VALUES($1,$2,$3,$4) ON CONFLICT(guild_id,server_id) DO UPDATE SET mime_type=EXCLUDED.mime_type,image=EXCLUDED.image,updated_at=NOW()',[gid,sid,type,data]);}
async function read(gid,sid){return(await(await ready()).query('SELECT mime_type,image FROM extinction_server_images WHERE guild_id=$1 AND server_id=$2',[gid,sid])).rows[0];}
async function remove(gid,sid){await(await ready()).query('DELETE FROM extinction_server_images WHERE guild_id=$1 AND server_id=$2',[gid,sid]);}
module.exports={validateUrl,decode,save,read,remove};
