import crypto from 'crypto';
import hosting from './hosting.cjs';
import {clean} from './collection-route';
import {encrypt} from './secure';
export const fields={name:'string',game:'string',platform:'string',map:'string',ip:'string',port:'string',nitradoId:'string',provider:'string',providerName:'string',panelUrl:'string',image:'string',enabled:'boolean',rconHost:'string',rconPort:'integer',rconPassword:'string',rconProtocol:'string',whitelistPath:'string',shopEnabled:'boolean',whitelistEnabled:'boolean',battlepassEnabled:'boolean'};
export function allServers(db,id){return [...new Map([...(db.connectedServers||[]),...(db.guilds[id]?.servers||[])].map(s=>[s.id,{...s,guildId:id}])).values()];}
export function publicServer(s){const {rconPassword,rcon_password,password,...data}=s;return {...data,rconConfigured:!!(rconPassword||rcon_password||password)};}
export function validateServer(body,previous={},guildId){const value=clean(body,fields);if(value.rconPassword)value.rconPassword=encrypt(value.rconPassword);else delete value.rconPassword;const s={...previous,...value,id:previous.id||crypto.randomUUID(),guildId,updatedAt:new Date().toISOString()};if(!s.name?.trim()||!s.game)throw new Error('Nom et jeu requis.');if(s.panelUrl&&!hosting.panelUrl(s))throw new Error('Adresse HTTPS du panel requise, sans identifiants dans le lien.');if(s.nitradoId&&!/^\d+$/.test(s.nitradoId))throw new Error('ID Nitrado numérique requis.');if(s.rconPort&&s.rconPort>65535)throw new Error('Port RCON invalide.');if(s.rconProtocol&&!['battleye','source'].includes(s.rconProtocol))throw new Error('Protocole RCON invalide.');s.nitradoServiceId=s.nitradoId||s.nitradoServiceId||'';return s;}
export function saveServers(db,id,servers){db.guilds[id]||={id,shop:[]};db.guilds[id].servers=servers;db.connectedServers=(db.connectedServers||[]).filter(s=>s.guildId!==id);db.connectedServers.push(...servers.filter(s=>s.nitradoServiceId));}
