import {readDb} from '../../../lib/db';
import {activeGuild,guarded} from '../../../lib/dashboard-auth';
import {decrypt} from '../../../lib/secure';
import games from '../../../lib/games.cjs';
import hosting from '../../../lib/hosting.cjs';
import {allServers} from '../../../lib/servers';
async function request(db,id,endpoint,method='GET'){const token=decrypt(db.nitradoAccounts[id]?.tokenEncrypted);if(!token)throw Object.assign(new Error('Connecte ton compte Nitrado dans Config propriétaires.'),{status:400});const r=await fetch(`https://api.nitrado.net${endpoint}`,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(30000),cache:'no-store'});if(!r.ok)throw Object.assign(new Error(`Nitrado a refusé la demande (${r.status}).`),{status:502});return r.json();}
export const GET=guarded(async req=>{const id=await activeGuild(),db=await readDb(),serverId=new URL(req.url).searchParams.get('serverId');if(!serverId){const d=await request(db,id,'/services');return Response.json({services:(d.data?.services||[]).map(s=>({id:String(s.id),name:s.details?.name||s.type,status:s.status}))});}const server=allServers(db,id).find(s=>s.id===serverId);if(server&&!hosting.isNitrado(server))throw new Error('Ce serveur utilise un autre hébergeur. Ouvre son panel depuis Actions serveur.');if(server&&games.capability(server).hosting===false)throw new Error('Ce jeu est disponible pour la communauté et les cartes, sans gestion de serveur Nitrado.');if(!server?.nitradoServiceId)throw new Error('Serveur Nitrado lié introuvable.');const d=await request(db,id,`/services/${server.nitradoServiceId}/gameservers`);const g=d.data?.gameserver||{};return Response.json({status:g.status,game:g.game,players:g.query?.player_current,slots:g.query?.player_max});});
export const POST=guarded(async req=>{const {serverId,action}=await req.json();if(!['restart','start','stop'].includes(action))throw new Error('Action invalide.');const id=await activeGuild(),db=await readDb(),server=allServers(db,id).find(s=>s.id===serverId);if(server&&!hosting.isNitrado(server))throw new Error('Ce serveur utilise un autre hébergeur. Ouvre son panel depuis Actions serveur.');if(server&&games.capability(server).hosting===false)throw new Error('Ce jeu est disponible pour la communauté et les cartes, sans gestion de serveur Nitrado.');if(!server?.nitradoServiceId)throw new Error('Serveur Nitrado lié introuvable.');await request(db,id,`/services/${server.nitradoServiceId}/gameservers/${action}`,'POST');return Response.json({ok:true,message:'Demande acceptée par Nitrado. Vérifie ensuite le statut du serveur.'});});
