const test=require('node:test'),assert=require('node:assert/strict'),atlas=require('../dashboard/lib/atlas.cjs'),tenant=require('../dashboard/lib/tenant.cjs');
function fixture(){return {maps:[{id:'m',guildId:'g',game:'ark',serverId:'s',name:'Monde',xMin:-100,xMax:100,yMin:-100,yMax:100,public:true}],atlasEntries:[]};}
test('public explorer returns only published entries on published maps and never player positions',()=>{
 const db=fixture();atlas.bulk(db,'g','m',[{name:'Rex',kind:'creature',x:-10,z:20,category:'Carnivore',sourceUrl:'https://example.com/source'}]);db.atlasEntries[0].public=true;db.livePlayers=[{id:'secret',x:10,z:20}];db.mapPins=[{id:'base',name:'Base privée'}];db.atlasEntries.push({...db.atlasEntries[0],id:'other',guildId:'other'},{...db.atlasEntries[0],id:'draft',public:false});const out=atlas.publicView(db,'ark');assert.equal(out.entries.length,1);assert.equal(out.entries[0].name,'Rex');assert.equal(out.entries[0].guildId,undefined);assert.equal(out.players,undefined);assert.equal(out.pins,undefined);db.maps[0].public=false;assert.equal(atlas.publicView(db,'ark').entries.length,0);
});
test('imports validate the entire batch before saving and are idempotent',()=>{
 const db=fixture(),r={name:'Métal',kind:'resource',x:0,z:-30};assert.equal(atlas.bulk(db,'g','m',[r]),1);assert.equal(atlas.bulk(db,'g','m',[r]),0);assert.throws(()=>atlas.bulk(db,'g','m',[r,{...r,x:999}]),/hors/);assert.equal(db.atlasEntries.length,1);assert.throws(()=>atlas.bulk(db,'other','m',[r]),/introuvable/);assert.throws(()=>atlas.bulk(db,'g','m',[{...r,sourceUrl:'javascript:alert(1)'}]),/HTTPS/);assert.throws(()=>atlas.bulk(db,'g','m',[{...r,sourceUrl:'https://user:pass@example.com'}]),/HTTPS/);assert.equal(db.atlasEntries[0].public,false);
});
test('manual entries can derive family from terrain without leaking unrelated guilds',()=>{
 const db=fixture();db.atlasEntries=[{id:'manual',mapId:'m',guildId:'g',name:'Rex',kind:'creature',x:0,z:0,public:true}];assert.equal(atlas.publicView(db,'ark').entries.length,1);assert.equal(atlas.publicView(db,'aniimo').entries.length,0);assert.equal(atlas.publicView(db,'ark','other').entries.length,0);const scoped=tenant.view({...db,restartBatches:[{id:'a',guildId:'g'},{id:'b',guildId:'other'}]},'other');assert.equal(scoped.atlasEntries.length,0);assert.equal(scoped.restartBatches.length,1);
});
