const test=require('node:test'),assert=require('node:assert/strict');
const games=require('../dashboard/lib/games.cjs'),quests=require('../dashboard/lib/quests.cjs'),live=require('../dashboard/lib/live-events.cjs'),bp=require('../dashboard/lib/battlepass.cjs'),economy=require('../dashboard/lib/economy.cjs'),ops=require('../dashboard/lib/game-operations.cjs'),multi=require('../dashboard/lib/multigame.cjs');
const gid='123456789012345',user='987654321098765',creator='222222222222222';
function fixture(game='ark'){const s={id:'s',guildId:gid,game,name:'Test'};return {s,db:{guilds:{[gid]:{servers:[s],progress:{[user]:{xp:0,claimed:[]}}}},battlepasses:{[gid]:{levels:[{id:'tier',level:1,xp:2,reward:7}]}},playerLinks:[{guildId:gid,serverId:'s',userId:user,uid:'killer',verified:true}],quests:[{id:'q',guildId:gid,game,serverId:'s',title:'Deux connexions',eventType:'connect',target:2,type:'daily',reward:10,xp:2}]}};}
function event(id){return {id,event:{type:'connect',player:'Joueur',playerUid:'killer',actors:[{uid:'killer',name:'Joueur'}],source:'game_bridge'}};}
test('all catalogue games support community rewards without pretending native delivery',()=>{for(const game of Object.keys(games.games)){const {s,db}=fixture(game);multi.shop({name:'Kit',game,serverId:'s',price:1,deliveryMode:'manual'},db,gid);live.apply(db,s,[event('a'),event('b')],'2026-10-04T10:00:00Z');assert.equal(db.bank.accounts[0].bank,17,game);assert.equal(db.guilds[gid].progress[user].xp,2);}});
test('automatic quests reject replay, renew daily and weekly at UTC boundaries',()=>{const {s,db}=fixture();live.apply(db,s,[event('a'),event('b')],'2026-10-04T23:00:00Z');live.apply(db,s,[event('a'),event('b'),event('c')],'2026-10-04T23:01:00Z');assert.equal(db.bank.accounts[0].bank,17);live.apply(db,s,[event('d'),event('e')],'2026-10-05T00:00:00Z');assert.equal(db.bank.accounts[0].bank,27);assert.equal(db.questProofs.length,2);assert.equal(quests.period({type:'weekly'},Date.parse('2026-10-04T23:59:59Z')),'2026-09-28');assert.equal(quests.period({type:'weekly'},Date.parse('2026-10-05T00:00:00Z')),'2026-10-05');});
test('quests isolate guild, game, server and verified identity',()=>{for(const mutate of [db=>db.quests[0].guildId='other',db=>db.quests[0].game='dayz_pc',db=>db.quests[0].serverId='other',db=>db.playerLinks[0].verified=false]){const {s,db}=fixture();mutate(db);live.apply(db,s,[event('a'),event('b')],'2026-10-04T10:00:00Z');assert.equal(db.bank,undefined);}});
test('late manual proof keeps its own reward period and prevents duplicate payout',()=>{const {db}=fixture();db.quests[0].eventType='manual';const proof={id:'proof',guildId:gid,userId:user,questId:'q',status:'pending',createdAt:'2026-10-03T12:00:00Z'};db.questProofs=[proof];economy.reviewProof(db,gid,'proof','approve','staff');assert.equal(proof.periodKey,'2026-10-03');db.questProofs.push({...proof,id:'dup',status:'pending'});assert.throws(()=>economy.reviewProof(db,gid,'dup','approve','staff'),/déjà attribuée/);assert.equal(db.bank.accounts[0].bank,17);});
test('game and server pass tracks do not award another game XP',()=>{const {db}=fixture();db.battlepasses[gid].levels=[{id:'ark',xp:2,reward:10,game:'ark',serverId:'s'},{id:'dayz',xp:2,reward:100,game:'dayz_pc'}];bp.earn(db,gid,user,2,{game:'dayz_pc',serverId:'other'},economy.credit);assert.equal(db.bank.accounts[0].bank,100);bp.earn(db,gid,user,2,{game:'ark',serverId:'s'},economy.credit);assert.equal(db.bank.accounts[0].bank,110);assert.equal(db.guilds[gid].progress[user].xp,4);});
test('premium entitlement pays reached levels once and revocation does not repeat rewards',()=>{const {db}=fixture(),config=db.battlepasses[gid];config.levels=[{id:'premium',xp:2,reward:50,premium:true}];bp.earn(db,gid,user,2,{game:'ark',serverId:'s'},economy.credit);assert.equal(db.bank,undefined);bp.mutate(config,{collection:'premium',userId:user},'POST');bp.earn(db,gid,user,0,{},economy.credit);assert.equal(db.bank.accounts[0].bank,50);bp.mutate(config,{collection:'premium',userId:user},'DELETE');bp.mutate(config,{collection:'premium',userId:user},'POST');bp.earn(db,gid,user,0,{},economy.credit);assert.equal(db.bank.accounts[0].bank,50);});
test('manual bounty needs evidence and verified eligible beneficiary and pays only once',()=>{const {db}=fixture();ops.change(db,gid,creator,100,'Seed');const b=ops.createBounty(db,gid,{serverId:'s',targetUid:'victim',creatorId:creator,amount:50});assert.throws(()=>ops.settleBounty(db,gid,b.id,user,'','staff'),/Preuve/);assert.throws(()=>ops.settleBounty(db,'other',b.id,user,'preuve','staff'),/inactive/);ops.settleBounty(db,gid,b.id,user,'https://proof.example/kill','staff');assert.equal(ops.account(db,gid,user).bank,50);assert.equal(ops.account(db,gid,creator).bank,50);assert.throws(()=>ops.settleBounty(db,gid,b.id,user,'preuve','staff'),/inactive/);});
test('shop and quests reject cross game configuration and unsupported automatic delivery',()=>{const {db}=fixture();assert.throws(()=>multi.shop({name:'Kit',game:'dayz_pc',serverId:'s',price:1},db,gid),/autre jeu/);assert.throws(()=>multi.shop({name:'Kit',game:'palworld',price:1,deliveryMode:'rcon'},db,gid),/ARK/);assert.throws(()=>quests.validate({title:'a',eventType:'kill',target:0}),/supérieur/);const json=require('../shared/community-commands').commands().map(c=>c.toJSON());assert.equal(new Set(json.map(c=>c.name)).size,json.length);assert.ok(json.find(c=>c.name==='quete').options[0].options.some(o=>o.name==='jeu'));});
