'use client';
import {useEffect,useState} from 'react';
import Maps from '../maps/page';
export default function Groups(){
 const [data,setData]=useState({groups:[],user:null}),[selected,setSelected]=useState(''),[name,setName]=useState(''),[token,setToken]=useState(''),[invite,setInvite]=useState(''),[message,setMessage]=useState(''),[login,setLogin]=useState(false),[busy,setBusy]=useState(false);
 const group=data.groups.find(g=>g.id===selected),owner=group?.ownerId===data.user?.id;
 async function load(){const r=await fetch('/api/groups',{cache:'no-store'});if(r.status===401){setLogin(true);return;}const d=await r.json();if(!r.ok)throw Error(d.error);setLogin(false);setData(d);setSelected(old=>d.groups.some(g=>g.id===old)?old:d.groups[0]?.id||'');}
 useEffect(()=>{const value=new URLSearchParams(location.search).get('invite')||sessionStorage.getItem('group-invite')||'';if(/^[a-f0-9]{64}$/.test(value)){setToken(value);sessionStorage.setItem('group-invite',value);history.replaceState(null,'','/groups');}load().catch(e=>setMessage(e.message));},[]);
 useEffect(()=>{setInvite('');setMessage('');},[selected]);
 async function send(endpoint,body,method='POST'){setBusy(true);setMessage('');try{const r=await fetch(endpoint,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error);if(d.token)setInvite(`${location.origin}/groups?invite=${d.token}`);if(body.action==='revoke')setInvite('');if(body.action==='join'){sessionStorage.removeItem('group-invite');setToken('');}await load();if(d.id)setSelected(d.id);setName('');setMessage('Enregistré.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const action=body=>send('/api/groups/'+group.id,body,'PATCH');
 return <><main className="max-w-7xl mx-auto p-5 lg:p-10"><nav className="flex gap-5 mb-8"><a href="/public">Cartes publiques</a><a href="/groups" className="font-bold">Mes groupes</a>{data.user&&<button onClick={async()=>{await fetch('/api/mod-auth/logout',{method:'POST'});location.href='/public';}}>Déconnexion</button>}</nav><h1 className="text-4xl font-black mb-4">Groupes de joueurs</h1><p className="text-white/70 mb-5">Crée ton groupe, invite tes amis et partage tes marqueurs privés sur les cartes publiques. Aucun rôle administrateur Discord requis. Les marqueurs sont actualisés toutes les 15 secondes.</p>{message&&<p role="status" className="card mb-4">{message}</p>}
 {login?<div className="card"><p className="mb-4">Connecte-toi avec ton compte Discord pour créer ou rejoindre un groupe.</p><a className="btn btn-primary" href="/api/mod-auth/login?next=groups">Connexion Discord</a></div>:<><div className="grid gap-4 md:grid-cols-2"><form className="card flex gap-3 flex-wrap" onSubmit={e=>{e.preventDefault();send('/api/groups',{name});}}><label className="flex-1">Nom du nouveau groupe<input required maxLength={80} className="input" value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={busy} className="btn btn-primary">Créer le groupe</button></form><form className="card flex gap-3 flex-wrap" onSubmit={e=>{e.preventDefault();let value=token;try{value=new URL(token).searchParams.get('invite')||token;}catch{}send('/api/groups',{action:'join',token:value});}}><label className="flex-1">Lien ou code d’invitation<input required className="input" value={token} onChange={e=>setToken(e.target.value)}/></label><button disabled={busy} className="btn btn-primary">Rejoindre</button></form></div>
 <label className="block my-5">Groupe actif<select className="input" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choisir un groupe</option>{data.groups.map(g=><option key={g.id} value={g.id}>{g.name} — {g.members.length} membres</option>)}</select></label>
 {group&&<section className="card"><h2 className="text-2xl font-bold mb-4">{group.name}</h2>{owner?<div className="flex gap-3 flex-wrap mb-4"><button disabled={busy} className="btn btn-primary" onClick={()=>action({action:'invite'})}>Créer / renouveler l’invitation</button><button disabled={busy} className="btn bg-white/10" onClick={()=>action({action:'revoke'})}>Désactiver l’invitation</button><form className="flex gap-2" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);action({action:'rename',name:form.get('name')});}}><input name="name" required maxLength={80} placeholder="Nouveau nom" className="input"/><button disabled={busy} className="btn bg-white/10">Renommer</button></form></div>:<button disabled={busy} className="btn bg-white/10 mb-4" onClick={()=>action({action:'leave'})}>Quitter le groupe</button>}
 {invite&&<label className="block mb-4">Invitation valable 7 jours (renouveler désactive l’ancien lien)<input readOnly className="input" value={invite} onFocus={e=>e.target.select()}/></label>}<h3 className="font-bold mb-3">Membres</h3>{group.members.map(m=><div key={m.id} className="flex flex-wrap gap-3 items-center mb-2"><span>{m.name}{m.id===group.ownerId?' — Créateur':''}</span>{owner&&m.id!==group.ownerId&&<><button disabled={busy} className="btn bg-white/10" onClick={()=>action({action:'remove',memberId:m.id})}>Exclure</button><button disabled={busy} className="btn bg-white/10" onClick={()=>action({action:'transfer',memberId:m.id})}>Transférer le groupe</button></>}</div>)}</section>}
 </>}
 </main>{group&&!login&&<Maps key={group.id} groupId={group.id}/>}</>;
}
