import crypto from 'crypto';
import {guarded,activeGuild} from '../../../lib/dashboard-auth';
import {readDb,writeDb} from '../../../lib/db';
import {allServers} from '../../../lib/servers';
import model from '../../../lib/map-model.cjs';
import templates from '../../../lib/map-templates.cjs';
export const GET=guarded(async()=>{const db=await readDb();return Response.json({players:(db.livePlayers||[]).map(p=>({id:p.id,serverId:p.serverId,name:p.name,x:p.x,z:p.z,lastSeen:p.lastSeen,online:p.online})),maps:db.maps||[],pins:db.mapPins||[],servers:allServers(db,await activeGuild()).map(s=>({id:s.id,name:s.name,game:s.game,map:s.map}))});});
async function mutate(req){const b=await req.json(),id=await activeGuild(),db=await readDb();db.maps||=[];const idx=db.maps.findIndex(m=>m.id===b.id);if(req.method!=='POST'&&idx<0)throw Object.assign(new Error('Carte introuvable.'),{status:404});if(req.method==='DELETE'){db.maps.splice(idx,1);db.mapPins=(db.mapPins||[]).filter(p=>p.mapId!==b.id);}else{const server=allServers(db,id).find(s=>s.id===b.serverId);if(!server)throw new Error('Serveur de ce Discord requis.');if(idx>=0&&(db.mapPins||[]).some(p=>p.mapId===b.id&&(p.x<b.xMin||p.x>b.xMax||p.y<b.yMin||p.y>b.yMax)))throw new Error('Les nouvelles limites excluent des marqueurs. Déplace-les avant de recalibrer.');const value=model.validateMap({id:idx>=0?db.maps[idx].id:crypto.randomUUID(),guildId:id,serverId:server.id,game:server.game,name:String(b.name||server.map||server.name).slice(0,160),imageUrl:String(b.imageUrl||''),xMin:b.xMin,xMax:b.xMax,yMin:b.yMin,yMax:b.yMax,flipY:b.flipY,public:b.public===true,publicPins:b.publicPins===true,worldCoordinates:b.worldCoordinates===true,...(b.templateId?templates.background(server.game,b.templateId,b.templateVariant):{})});if(idx>=0)db.maps[idx]=value;else db.maps.push(value);}await writeDb(db);return Response.json({ok:true});}
export const POST=guarded(mutate),PATCH=guarded(mutate),DELETE=guarded(mutate);
