'use client';
import {useEffect,useState} from 'react';
export default function AtlasImport(){
 const [maps,setMaps]=useState([]),[mapId,setMapId]=useState(''),[file,setFile]=useState(null),[proto,setProto]=useState(null),[source,setSource]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/maps',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setMaps(d.maps||[])}).catch(e=>setMessage(e.message));},[]);
 async function post(body){const r=await fetch('/api/atlas-import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Import refusé.');return d;}
 function xml(text){if(/<!DOCTYPE|<!ENTITY/i.test(text))throw new Error('DTD et entités XML non acceptées.');const d=new DOMParser().parseFromString(text,'application/xml');if(d.querySelector('parsererror'))throw new Error('XML invalide.');return d;}
 async function run(){setBusy(true);try{
  if(!file||file.size>8*1024*1024||proto?.size>8*1024*1024)throw new Error('Fichiers de 8 Mo maximum requis.');
  let rows;const text=await file.text();
  if(file.name.toLowerCase().endsWith('.xml')){
   const m=maps.find(m=>m.id===mapId);if(!m?.game?.startsWith('dayz_')||m.worldCoordinates!==true||!proto)throw new Error('Carte DayZ en coordonnées monde vérifiées et mapgroupproto.xml requis.');
   const groups=xml(text),defs=xml(await proto.text());if(groups.documentElement.tagName!=='map'||defs.documentElement.tagName!=='prototype')throw new Error('mapgrouppos.xml et mapgroupproto.xml attendus.');
   const byName=new Map([...defs.querySelectorAll('prototype > group')].map(g=>[g.getAttribute('name'),[...g.querySelectorAll('usage')].map(u=>u.getAttribute('name')).filter(Boolean)]));
   rows=[...groups.querySelectorAll('map > group')].flatMap(g=>{const name=g.getAttribute('name'),tags=byName.get(name),p=(g.getAttribute('pos')||'').trim().split(/\s+/).map(Number);if(!tags?.length||p.length!==3||!p.every(Number.isFinite))return [];return [{name,kind:'loot',category:tags.includes('Military')?'Military':tags.includes('Medic')?'Medic':tags[0],x:p[0],z:p[2],sourceUrl:source,notes:'Bâtiment à potentiel de loot selon les fichiers CE importés. Les points intérieurs, objets présents et spawns garantis ne sont pas déterminés.'}];});
  }else{rows=JSON.parse(text);if(!Array.isArray(rows))throw new Error('Tableau JSON de points requis.');rows=rows.map(r=>({...r,sourceUrl:r.sourceUrl||source}));}
  if(!rows.length||rows.length>20000)throw new Error('De 1 à 20 000 points requis.');let count=0;
  for(let i=0;i<rows.length;i+=200){const d=await post({mapId,rows:rows.slice(i,i+200)});count+=d.count;setMessage(`${Math.min(i+200,rows.length)} / ${rows.length} points examinés…`);}
  setMessage(`${count} points ajoutés comme brouillons. Les points déjà importés sont ignorés. Vérifie les données avant de les publier.`);
 }catch(e){setMessage(e.message+' Les lots déjà enregistrés restent en brouillon ; relancer ignore leurs doublons.');}finally{setBusy(false);}}
 async function publish(){setBusy(true);try{const d=await post({action:'publish',mapId});setMessage(`${d.count} points publiés sur cette carte. Ils deviennent visibles dans l’explorateur public.`);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <section className="card my-6 space-y-4"><h3 className="text-2xl font-bold">Importer les emplacements</h3><p>JSON : tableau de points avec name, kind (creature/resource/loot), category, x, z, conditions et sourceUrl. DayZ : importe les fichiers mapgrouppos.xml et mapgroupproto.xml du serveur sur une carte calibrée en coordonnées monde.</p><label className="block">Carte du serveur<select disabled={busy} className="input" value={mapId} onChange={e=>setMapId(e.target.value)}><option value="">Choisir une carte</option>{maps.map(m=><option key={m.id} value={m.id}>{m.name} — {m.game}</option>)}</select></label><label className="block">Points JSON ou mapgrouppos.xml<input disabled={busy} className="input" type="file" accept=".json,.xml" onChange={e=>setFile(e.target.files?.[0])}/></label><label className="block">DayZ uniquement : mapgroupproto.xml<input disabled={busy} className="input" type="file" accept=".xml" onChange={e=>setProto(e.target.files?.[0])}/></label><label className="block">Source HTTPS des données (facultative)<input disabled={busy} className="input" type="url" value={source} onChange={e=>setSource(e.target.value)}/></label><div className="flex flex-wrap gap-3"><button disabled={busy||!mapId||!file} className="btn btn-primary" onClick={run}>Importer en brouillon</button><button disabled={busy||!mapId} className="btn bg-white/10" onClick={publish}>Publier tous les points de cette carte</button></div><p>La publication est volontaire et nécessite une carte publique. Utilise ensuite l’éditeur ci-dessous pour corriger, retirer ou masquer les points.</p>{message&&<p role="status">{message}</p>}</section>;
}
