'use client';
import {useState,useEffect} from 'react';
import icons from '../lib/resource-icons.cjs';
import breed from '../lib/pal-breeding.cjs';
import crafting from '../lib/crafting-plan.cjs';
import catalog from '../lib/catalog-model.cjs';
const labels={Fire:'Feu',Water:'Eau',Dark:'Ombre',Grass:'Plante',Electric:'Électricité',Ice:'Glace',Earth:'Terre',Dragon:'Dragon',Neutral:'Neutre','attributes-fire':'Feu','attributes-water':'Eau','attributes-dark':'Ombre','attributes-light':'Lumière','attributes-ice':'Glace','attributes-earth':'Terre','attributes-grass':'Plante','attributes-wind':'Vent','attributes-electric':'Électricité','attributes-rock':'Roche','attributes-holy':'Lumière','position-dps':'Dégâts','position-breaker':'Rupture','position-healer':'Soin','position-support':'Soutien','position-energy':'Énergie','position-break':'Rupture','position-heal':'Soin','position-sup':'Soutien',hp:'PV',HP:'PV',physicalAttack:'Attaque physique',magicAttack:'Attaque magique',physicalDefense:'Défense physique',magicDefense:'Défense magique',haste:'Vitesse',Weight:'Poids',Gold:'Valeur',EncumbranceWeight:'Poids',ArmourValue:'Armure',MaxStackSize:'Pile maximale',ArmorPen:'Pénétration d’armure',ItemTier:'Tier',Handiwork:'Travail manuel',Transporting:'Transport',Mining:'Extraction',Kindling:'Allumage',Watering:'Arrosage',Planting:'Plantation',Gathering:'Collecte',Lumbering:'Abattage',MedicineProduction:'Médecine',Cooling:'Refroidissement',Farming:'Ferme','Generating Electricity':'Électricité',Construction:'Construction',Decoration:'Décoration',Survival:'Survie',Weapons:'Armes',Armor:'Armures',Religion:'Religion',BuildingItem:'Construction',Ingredient:'Ingrédient',Material:'Matériau',Weapon:'Arme',Consumable:'Consommable',Accessory:'Accessoire',Attack:'Attaque',Defense:'Défense',Melee:'Corps à corps',Ranged:'À distance',Speed:'Vitesse',Run:'Course',Ride:'Monture',Walk:'Marche'};
const titles={items:'Objets',models:'Modèles et bâtiments',recipes:'Objets et recettes',resources:'Ressources et matériaux',team:'Mon équipe',collection:'Ma collection',breeding:'Élevage et reproduction',knowledge:'Connaissances et technologies',buildings:'Constructions et recettes',habitats:'Habitats par région',codex:'Encyclopédie'};
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function Artwork({entry,className=''}){
 const [failed,setFailed]=useState(false);
 useEffect(()=>setFailed(false),[entry.imageUrl]);
 return <div className={'relative flex items-center justify-center '+className}>{entry.imageUrl&&!failed?<img src={entry.imageUrl} loading="lazy" alt={entry.name} className="w-full h-full object-contain" onError={()=>setFailed(true)}/>:<span aria-hidden="true" className="text-5xl">{icons.icon({...entry,kind:entry.kind||'loot'})}</span>}</div>;
}
export default function LibraryCatalog({game,data,view='codex',onLocations}){
 const [limit,setLimit]=useState(120),[query,setQuery]=useState(''),[element,setElement]=useState('all'),[role,setRole]=useState('all'),[work,setWork]=useState('all'),[category,setCategory]=useState('all'),[habitat,setHabitat]=useState('all');
 const [selected,setSelected]=useState(null),[saved,setSaved]=useState({caught:[],team:[],plan:[]}),[loadedStorage,setLoadedStorage]=useState(''),[parent1,setParent1]=useState(''),[parent2,setParent2]=useState(''),[quantity,setQuantity]=useState(1),[notice,setNotice]=useState('');
 const storage='extinction-companion-'+game,creatures=data?.creatures||[],teamLimit=game==='aniimo'?4:5;
 useEffect(()=>{
  let value={caught:[],team:[],plan:[]};try{const old=JSON.parse(localStorage.getItem(storage)||'{}');value.caught=Array.isArray(old.caught)?old.caught.filter(x=>typeof x==='string'):[];value.team=Array.isArray(old.team)?old.team.filter(x=>typeof x==='string').slice(0,teamLimit):[];if(Array.isArray(old.plan)){crafting.totals(old.plan);value.plan=old.plan;}}catch{}
  setSaved(value);setLoadedStorage(storage);
 },[storage,teamLimit]);
 useEffect(()=>{if(loadedStorage===storage)try{localStorage.setItem(storage,JSON.stringify(saved));}catch{setNotice('Stockage indisponible ; tes choix sont conservés pour cette session.');}},[saved,loadedStorage,storage]);
 useEffect(()=>{setSelected(null);setQuery('');setElement('all');setRole('all');setWork('all');setCategory('all');setHabitat('all');},[view]);
 useEffect(()=>setLimit(120),[query,element,role,work,category,habitat,view]);
 useEffect(()=>{function key(e){if(e.key==='Escape')setSelected(null);}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 function open(item){setSelected(item);setQuantity(1);}
 function toggle(key,id){if(key==='team'&&!saved.team.includes(id)&&saved.team.length>=teamLimit){setNotice(`Équipe limitée à ${teamLimit} créatures.`);return;}setSaved({...saved,[key]:saved[key].includes(id)?saved[key].filter(x=>x!==id):[...saved[key],id]});}
 const source=catalog.rows(data,view),rows=source.filter(c=>norm([c.name,c.number,...(c.habitats||[])].join(' ')).includes(norm(query))&&(element==='all'||c.elements?.includes(element))&&(role==='all'||c.roles?.includes(role))&&(work==='all'||c.work?.some(w=>w.name===work))&&(category==='all'||c.category===category||c.categories?.includes(category))&&(habitat==='all'||c.habitats?.includes(habitat))&&(view!=='collection'||saved.caught.includes(c.id))&&(view!=='team'||saved.team.includes(c.id)));
 const result=data.breeding?breed.offspring(data,parent1,parent2):[],totals=crafting.totals(saved.plan),categories=[...new Set(source.flatMap(c=>c.categories||[c.category]).filter(Boolean))].sort(),habitats=[...new Set(creatures.flatMap(c=>c.habitats||[]))].sort();
 const related=selected?catalog.related(data,selected):null,isCreature=selected&&creatures.some(c=>c.id===selected.id);
 function addRecipe(recipe){try{const plan=[...saved.plan,{...recipe,quantity}];crafting.totals(plan);setSaved({...saved,plan});setNotice('Recette ajoutée au plan.');}catch(error){setNotice(error.message);}}
 const filter=(name,value,set,values)=><label>{name}<select className="input" value={value} onChange={e=>set(e.target.value)}><option value="all">Tous</option>{values.map(v=><option key={v} value={v}>{labels[v]||v}</option>)}</select></label>;
 return <section className="my-5">
  <h2 className="text-2xl font-black mb-4">{titles[view]||'Encyclopédie'}</h2>
  <p className="text-white/60 text-sm mb-4">{data.version}</p>
  {data.licenseUrl&&<a className="underline text-sm" href={data.licenseUrl}>Source et licence des données</a>}
  {['team','collection'].includes(view)&&<p>Collection et équipe enregistrées sur cet appareil.</p>}
  {view==='habitats'&&<p className="card mb-4">Régions citées par l’index officiel. Les coordonnées précises et conditions de chaque apparition ne sont pas fournies par cette liste.</p>}
  {view==='breeding'?<div className="card"><p>Choisis deux parents pour consulter leur résultat dans la version du catalogue.</p><div className="grid sm:grid-cols-2 gap-3 my-4">{[[parent1,setParent1],[parent2,setParent2]].map(([value,set],i)=><label key={i}>Parent {i+1}<select className="input" value={value} onChange={e=>set(e.target.value)}><option value="">Sélectionner</option>{creatures.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>)}</div>{result.map(c=><button type="button" key={c.id} className="card" onClick={()=>open(c)}><Artwork entry={c} className="h-32"/><b>{c.name}</b></button>)}{parent1&&parent2&&!result.length&&<p>Paire non renseignée dans la source.</p>}</div>:<>
   <input className="input my-3" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher par nom ou numéro…"/>
   <div className="flex flex-wrap gap-3 mb-4">
    {source.some(c=>c.elements?.length)&&filter('Élément',element,setElement,[...new Set(source.flatMap(c=>c.elements||[]))])}
    {source.some(c=>c.roles?.length)&&filter('Rôle',role,setRole,[...new Set(source.flatMap(c=>c.roles||[]))])}
    {source.some(c=>c.work?.length)&&filter('Travail',work,setWork,[...new Set(source.flatMap(c=>(c.work||[]).map(w=>w.name)))])}
    {categories.length>0&&filter('Catégorie',category,setCategory,categories)}
    {source.some(c=>c.habitats?.length)&&filter('Habitat',habitat,setHabitat,habitats)}
   </div>
   <p className="mb-3 text-white/60">{rows.length} résultats</p>
   <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">{rows.slice(0,limit).map(c=><button type="button" key={c.id} className="rounded-2xl overflow-hidden border border-purple-400/25 bg-[#172033] text-left hover:border-purple-400" onClick={()=>open(c)}>
    <div className="h-32 sm:h-40 relative bg-gradient-to-br from-purple-950/60 to-slate-900 p-2"><span className="absolute z-10 left-3 top-2 text-xs text-purple-200">{c.number?'#'+c.number:''}</span><Artwork entry={{...c,kind:c.kind||(['codex','team','collection','habitats'].includes(view)?'creature':'loot')}} className="w-full h-full"/></div>
    <div className="p-3"><b className="block">{c.name}</b><p className="text-xs text-purple-200 mt-2">{[...(c.elements||[]),...(c.roles||[])].map(e=>labels[e]||e).join(' · ')}</p>{c.category&&<p className="text-xs text-white/60">{labels[c.category]||c.category}</p>}{Number.isFinite(c.level)&&<p className="text-xs">Niveau {c.level} · {c.cost} points</p>}{c.work?.length>0&&<p className="text-xs text-white/60 mt-1">{c.work.slice(0,3).map(w=>(labels[w.name]||w.name)+' '+w.level).join(' · ')}</p>}{view==='habitats'&&<p className="text-xs mt-2">{(c.habitats||[]).join(' · ')||'Habitat non renseigné'}</p>}{saved.caught.includes(c.id)&&<p className="text-xs text-emerald-300">✓ Dans ma collection</p>}</div>
   </button>)}</div>
   {rows.length>limit&&<button type="button" className="btn bg-white/10 mt-4" onClick={()=>setLimit(limit+120)}>Afficher les suivants ({Math.min(limit,rows.length)} / {rows.length})</button>}{!rows.length&&<p className="card">Aucun résultat pour ces filtres.</p>}
  </>}
  {notice&&<p role="status" className="card my-3">{notice}</p>}
  {selected&&<div role="dialog" aria-modal="true" aria-label={selected.name} className="fixed inset-0 z-[80] bg-black/85 p-4 overflow-y-auto"><article className="max-w-2xl mx-auto rounded-3xl border border-purple-500/40 bg-[#111827] p-5 my-5">
   <button type="button" autoFocus className="btn bg-white/10 float-right" onClick={()=>setSelected(null)}>Fermer</button><Artwork entry={{...selected,kind:selected.kind||(isCreature?'creature':'loot')}} className="h-48 max-w-full mx-auto"/>
   <h3 className="text-2xl font-black text-purple-300 mt-3">{selected.name}</h3><p>{selected.number?'#'+selected.number:''} {selected.form||''}</p><p>{[...(selected.elements||[]),...(selected.roles||[])].map(e=>labels[e]||e).join(' · ')}</p>
   {selected.categories&&<p>Catégories : {selected.categories.map(c=>labels[c]||c).join(', ')}</p>}{selected.category&&<p>Catégorie : {labels[selected.category]||selected.category}</p>}
   {selected.usage&&<p>Usages de loot : {selected.usage.join(', ')}</p>}{selected.nominals&&Object.values(selected.nominals).every(n=>n<=0)&&<p className="text-white/60">Cette classe n’est pas prévue dans le loot automatique de ces catalogues ; sa disponibilité peut dépendre de la fabrication, de la récolte ou d’événements.</p>}{selected.maps?.length>0&&<p>Catalogues : {selected.maps.map(m=>({'builtin-dayz-chernarusplus':'Chernarus','builtin-dayz-enoch':'Livonia','builtin-dayz-sakhal':'Sakhal'}[m]||m)).join(', ')}</p>}{selected.tiers?.length>0&&<p>Tiers : {selected.tiers.join(', ')}</p>}
   {Number.isFinite(selected.level)&&<p>Niveau requis : {selected.level} · Coût : {selected.cost} points</p>}{selected.dlc&&selected.dlc!=='None'&&<p>DLC : {selected.dlc}</p>}
   {catalog.stats(selected.stats).length>0&&<div className="card mt-3"><h4 className="font-bold">Statistiques de base de la source</h4>{catalog.stats(selected.stats).map(s=><p key={s.name}>{s.name.split(' / ').map(k=>labels[k]||k).join(' / ')} : {s.value}</p>)}</div>}
   {selected.work?.length>0&&<div className="card mt-3"><h4 className="font-bold">Aptitudes au travail</h4>{selected.work.map(w=><p key={w.name}>{labels[w.name]||w.name} : niveau {w.level}</p>)}</div>}
   {selected.drops?.length>0&&<div className="card mt-3"><h4 className="font-bold">Butin documenté</h4>{selected.drops.map(d=><p key={d.name}>{icons.icon({name:d.name,kind:'resource'})} {d.name}{Number.isFinite(d.min)?` : ${d.min}–${d.max}`:''}{Number.isFinite(d.rate)?` (${d.rate} % dans la source)`:''}</p>)}</div>}
   {selected.habitats?.length>0&&<div className="card mt-3"><h4 className="font-bold">Habitats officiels</h4>{selected.habitats.map(h=><p key={h}>{h}</p>)}</div>}
   {Object.entries(selected.habitatImages||{}).map(([time,url])=><figure key={time} className="card mt-3"><figcaption className="font-bold">Habitat {time==='day'?'de jour':time==='night'?'de nuit':time} · zones documentées</figcaption><a href={url} target="_blank" rel="noopener noreferrer"><img src={url} loading="lazy" alt={'Zones d’habitat de '+selected.name+' '+time} className="w-full rounded-xl"/></a><p className="text-sm text-white/60">Carte de la version du catalogue ; aucune présence en temps réel.</p></figure>)}
   {selected.evolution?.length>0&&<div className="card mt-3"><h4 className="font-bold">Famille d’évolution</h4><div className="grid grid-cols-2 gap-2">{selected.evolution.map((e,i)=><button type="button" key={e.name+'-'+i} onClick={()=>{const next=creatures.find(c=>c.name===e.name);if(next)open(next);}} disabled={!creatures.some(c=>c.name===e.name)}><Artwork entry={e} className="h-20"/>{e.name} · stade {e.stage}</button>)}</div></div>}
   {(selected.abilities?.length>0||selected.skills?.length>0)&&<div className="card mt-3"><h4 className="font-bold">Compétences et capacités</h4>{(selected.abilities||selected.skills).map((s,i)=><div key={s.name+'-'+i} className="flex items-center gap-3 my-2">{s.imageUrl&&<Artwork entry={s} className="w-12 h-12 shrink-0"/>}<p>{s.name}{Number.isFinite(s.level)?` · niveau ${s.level}`:''}{Number.isFinite(s.power)?` · puissance ${s.power}`:''}{Number.isFinite(s.cooldown)?` · recharge ${s.cooldown} s`:''}</p></div>)}</div>}
   {(related.unlocks.length>0||related.prerequisites.length>0)&&<div className="card mt-3">{related.prerequisites.length>0&&<><h4 className="font-bold">Prérequis</h4>{related.prerequisites.map(k=><button type="button" key={k.id} className="block underline my-2" onClick={()=>open(k)}>{k.name}</button>)}</>}<h4 className="font-bold">Débloque</h4>{related.unlocks.map(r=><button type="button" key={r.id} className="block underline my-2" onClick={()=>open(r)}>{r.name}</button>)}</div>}
   {selected.ingredients?.length>0&&<div className="card mt-3"><h4 className="font-bold">Matériaux par fabrication · rendement {selected.yield}</h4>{selected.ingredients.map(i=><p key={i.name}>{i.name} × {i.amount}</p>)}{selected.station&&<p>Station de la source : {selected.station}</p>}{Number.isFinite(selected.craftTime)&&<p>Temps de base : {selected.craftTime} s</p>}{selected.results?.length>1&&<p>Produits : {selected.results.map(r=>r.name+' × '+r.amount).join(' · ')}</p>}<label>Quantité à fabriquer<input className="input my-3" type="number" min="1" step="1" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><button type="button" className="btn btn-primary" onClick={()=>addRecipe(selected)}>Ajouter au plan de matériaux</button></div>}
   {view==='resources'&&(related.drops.length>0||related.recipes.length>0)&&<div className="card mt-3"><h4 className="font-bold">Obtention et utilisation</h4>{related.drops.map(c=><button type="button" key={c.id} className="block underline my-2" onClick={()=>open(c)}>Butin de {c.name}</button>)}{related.recipes.slice(0,100).map(r=><button type="button" key={r.id} className="block underline my-2" onClick={()=>open(r)}>Utilisé dans {r.name}</button>)}{related.recipes.length>100&&<p>{related.recipes.length} recettes utilisent cette ressource ; les 100 premières sont affichées.</p>}</div>}
   {isCreature&&<div className="flex flex-wrap gap-3 my-4"><button type="button" className="btn bg-white/10" onClick={()=>toggle('caught',selected.id)}>{saved.caught.includes(selected.id)?'Retirer de la collection':'Ajouter à ma collection'}</button><button type="button" className="btn bg-white/10" onClick={()=>toggle('team',selected.id)}>{saved.team.includes(selected.id)?'Retirer de l’équipe':'Ajouter à mon équipe'}</button>{onLocations&&<button type="button" className="btn btn-primary" onClick={()=>{onLocations(selected.name);setSelected(null);}}>Rechercher sur la carte</button>}</div>}
   {selected.imageSourceUrl&&<a href={selected.imageSourceUrl} target="_blank" rel="noopener noreferrer" className="block underline my-3">Source de l’image et mentions d’utilisation</a>}{selected.sourceUrl&&<a href={selected.sourceUrl} target="_blank" rel="noopener noreferrer" className="underline">Consulter la fiche source et les données complémentaires</a>}
  </article></div>}
  {saved.plan.length>0&&<article className="card mt-6"><h3 className="text-xl font-bold">Plan de fabrication</h3><p className="text-white/60 text-sm">Enregistré sur cet appareil. Coûts directs, sans bonus de serveur ou décomposition des ingrédients.</p>{saved.plan.map((r,i)=><p key={i}>{r.name} × {r.quantity} <button type="button" className="underline" onClick={()=>setSaved({...saved,plan:saved.plan.filter((_,j)=>j!==i)})}>Retirer</button></p>)}<h4 className="font-bold mt-4">Total des matériaux directs</h4>{totals.map(t=><p key={t.name}>{t.name} × {t.amount}</p>)}</article>}
 </section>;
}
