'use client';
import {useEffect,useState} from 'react';
export default function ModerationNetwork(){const [networks,setNetworks]=useState([]),[name,setName]=useState(''),[code,setCode]=useState(''),[active,setActive]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[report,setReport]=useState({game:'dayz_pc',playerUid:'',playerName:'',reason:'',evidence:''}),[serverId,setServerId]=useState('');
async function load(){const r=await fetch('/api/moderation-network'),d=await r.json();if(!r.ok)throw new Error(d.error);setNetworks(d);setActive(v=>d.some(n=>n.id===v)?v:d[0]?.id||'');}
useEffect(()=>{load().catch(e=>setMessage(e.message))},[]);
async function send(body){setBusy(true);setMessage('');try{const r=await fetch('/api/moderation-network',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(d.code?`Invitation valable 7 jours : ${d.code}`:d.message||'Enregistré.');await load();}catch(e){setMessage(e.message)}finally{setBusy(false)}}
const n=networks.find(n=>n.id===active);
return <section className="card mt-6 space-y-5"><h3 className="text-2xl font-black">Réseaux Interpol entre communautés</h3><p>Chaque Discord rejoint volontairement un réseau. Les signalements sont des dossiers publiés par ses membres ; le staff de chaque serveur choisit de les appliquer. Un retrait du signalement ne retire pas automatiquement un ban déjà appliqué dans un jeu.</p>{message&&<p role="status" className="break-all">{message}</p>}
<form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();send({action:'create',name})}}><input className="input" placeholder="Nom du nouveau réseau" required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/><button disabled={busy} className="btn btn-primary">Créer le réseau</button></form>
<form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();send({action:'join',code})}}><input className="input" placeholder="Code d’invitation du réseau" required value={code} onChange={e=>setCode(e.target.value.trim())}/><button disabled={busy} className="btn bg-white/10">Rejoindre ce réseau</button></form>
<select className="input" value={active} onChange={e=>setActive(e.target.value)}><option value="">Choisir un réseau</option>{networks.map(n=><option key={n.id} value={n.id}>{n.name} — {n.members.length} communautés</option>)}</select>
{n&&<><div className="flex gap-3"><button disabled={busy} className="btn bg-white/10" onClick={()=>send({action:'invite',networkId:n.id})}>Renouveler l’invitation (propriétaire)</button><button disabled={busy} className="btn bg-white/10" onClick={()=>send({action:'leave',networkId:n.id})}>Quitter le réseau</button></div>
<form onSubmit={e=>{e.preventDefault();send({action:'publish',networkId:n.id,...report})}} className="grid gap-3 sm:grid-cols-2"><h4 className="font-bold sm:col-span-2">Publier un signalement examiné par le staff</h4><select className="input" value={report.game} onChange={e=>setReport({...report,game:e.target.value})}>{['dayz_pc','dayz_ps','dayz_xbox','ark','arma','palworld','conan','7dtd'].map(g=><option key={g}>{g}</option>)}</select>{[['playerUid','UID exact du joueur'],['playerName','Pseudo'],['reason','Motif documenté'],['evidence','Lien HTTPS vers les preuves']].map(([k,label])=><label key={k}>{label}<input className="input" required={['playerUid','reason'].includes(k)} value={report[k]} maxLength={2000} onChange={e=>setReport({...report,[k]:e.target.value})}/></label>)}<button disabled={busy} className="btn btn-primary">Publier dans ce réseau</button></form>
<label>ID exact du serveur local pour appliquer un signalement<input className="input" value={serverId} onChange={e=>setServerId(e.target.value)}/></label>
{n.reports.slice().reverse().map(r=><div className="rounded-xl bg-black/30 p-4 space-y-2" key={r.id}><b>{r.playerName} — {r.game} — {r.status}</b><p className="break-all">UID : {r.playerUid}</p><p>{r.reason}</p><p>Communauté source : {r.sourceGuildId}</p>{r.evidence&&<a className="underline" href={r.evidence} target="_blank" rel="noopener noreferrer">Voir les preuves</a>}<div className="flex gap-3">{r.status==='published'&&<><button disabled={busy||!serverId} className="btn bg-red-700" onClick={()=>send({action:'apply',networkId:n.id,reportId:r.id,serverId})}>Appliquer sur ce serveur</button><button disabled={busy} className="btn bg-white/10" onClick={()=>send({action:'withdraw',networkId:n.id,reportId:r.id})}>Retirer (auteur / propriétaire)</button></>}</div></div>)}</>}
</section>}
