'use client';
import {useEffect,useState} from 'react';
const gameNames={dayz_pc:'DayZ PC',dayz_ps:'DayZ PlayStation',dayz_xbox:'DayZ Xbox',ark:'ARK',arma:'Arma Reforger',palworld:'Palworld',conan:'Conan Exiles','7dtd':'7 Days to Die',aniimo:'Aniimo'};
export default function ModuleEditor({endpoint,title='Gestion',fields,readKey,listKey,allowDelete=true,basicFields=null}) {
  const [items,setItems]=useState([]),[form,setForm]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
  async function load(){const r=await fetch(endpoint,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Chargement impossible.');const values=readKey?d[readKey]:d;setItems(Array.isArray(values)?values:[]);setLoaded(true);}
  useEffect(()=>{setLoaded(false);setError('');load().catch(e=>setError(e.message))},[endpoint]);
  async function save(event,remove=false){event.preventDefault();setBusy(true);setError('');try{const body={...form};for(const f of fields){if(['number','integer','numberSigned'].includes(f.type)&&body[f.name]!==undefined&&body[f.name]!=='')body[f.name]=Number(body[f.name]);if(f.type==='boolean'&&body[f.name]===undefined)body[f.name]=f.defaultValue??(f.name==='enabled');if(f.type==='strings'&&typeof body[f.name]==='string')body[f.name]=body[f.name].split(',').map(x=>x.trim()).filter(Boolean);}if(listKey)body.collection=listKey;const r=await fetch(endpoint,{method:remove?'DELETE':form.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Enregistrement impossible.');setForm({});await load();if(endpoint==='/api/servers')window.dispatchEvent(new Event('servers-updated'));setError(remove?'Élément supprimé.':'Enregistré.');}catch(e){setError(e.message)}finally{setBusy(false)}}
  const renderField=f=><label key={f.name} className="block">{f.label}{f.type==='boolean'?<input type="checkbox" className="ml-3" checked={form[f.name]??f.defaultValue??(f.name==='enabled')} onChange={e=>setForm({...form,[f.name]:e.target.checked})}/>:f.name==='game'||f.options?<select className="input mt-2" value={form[f.name]||''} required={f.required} onChange={e=>setForm({...form,[f.name]:e.target.value})}><option value="">Choisir</option>{Object.entries(f.name==='game'?gameNames:f.options).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select>:<input className="input mt-2" required={f.required} type={f.type==='password'?'password':['number','integer','numberSigned'].includes(f.type)?'number':'text'} min={f.type==='numberSigned'?undefined:['number','integer'].includes(f.type)?0:undefined} step={['number','numberSigned'].includes(f.type)?'any':undefined} maxLength={4000} value={Array.isArray(form[f.name])?form[f.name].join(', '):form[f.name]??''} onChange={e=>setForm({...form,[f.name]:e.target.value})}/>}</label>;
  return <section id={basicFields?'server-editor':undefined} className="card my-6 space-y-4"><h3 className="text-2xl font-black">{title}</h3>{error&&<p role="status">{error}</p>}{!loaded&&<button type="button" disabled={busy} className="btn bg-white/10" onClick={()=>load().catch(e=>setError(e.message))}>Réessayer le chargement</button>}<form onSubmit={save} className="grid gap-4 sm:grid-cols-2">{fields.filter(f=>!basicFields||basicFields.includes(f.name)).map(renderField)}{basicFields&&<details className="sm:col-span-2 rounded-2xl border border-white/20 p-4"><summary className="cursor-pointer font-bold">Connexion et réglages avancés</summary><p className="my-3 text-white/70">Renseigne uniquement les accès nécessaires aux modules choisis. Un champ secret vide conserve le secret enregistré.</p><div className="grid gap-4 sm:grid-cols-2">{fields.filter(f=>!basicFields.includes(f.name)).map(renderField)}</div></details>}<div className="sm:col-span-2 flex gap-3"><button className="btn btn-primary" disabled={busy||!loaded}>{busy?'En cours…':form.id?'Enregistrer les modifications':'Ajouter'}</button>{form.id&&<button type="button" className="btn bg-white/10" onClick={()=>setForm({})}>Annuler</button>}{form.id&&allowDelete&&<button type="button" className="btn bg-red-700" disabled={busy} onClick={e=>save(e,true)}>Supprimer</button>}</div></form><div className="space-y-3">{items.map(item=><div key={item.id} className="flex items-center justify-between gap-4 rounded-xl bg-black/30 p-3"><div><b>{item.name||item.title||item.subject||item.player||item.itemName||item.code||item.id}</b><p className="text-sm text-white/60">{gameNames[item.game]||''} {item.server||item.serverId||''} {item.status||''} {item.amount!==undefined?`• ${item.amount}`:''} {item.treasury!==undefined?`• Trésorerie ${item.treasury}`:''}</p>{item.error&&<p className="text-amber-300 text-sm">{item.error}</p>}</div><button className="btn bg-white/10" onClick={()=>{setForm({...item});setError('')}}>Modifier</button></div>)}</div></section>;
}
