'use client';
import {useEffect,useState} from 'react';
const labels={requested:'En file',waiting_stop:'Attente de l’arrêt',waiting_start:'Attente du démarrage',loading:'Chargement du monde',complete:'Fichier nettoyé — apparition à vérifier',uncertain:'Reprise à vérifier',reviewed:'Reprise vérifiée',rejected:'Préparation refusée avant intervention'};
export default function RestartDeliveries(){
 const [rows,setRows]=useState([]),[note,setNote]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/restart-shop',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Lots indisponibles.');setRows(d);}catch(e){setMessage(e.message);}}
 useEffect(()=>{load();},[]);
 async function recover(b){setBusy(true);try{const r=await fetch('/api/restart-shop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'recover',serverId:b.serverId,batchId:b.id,note})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Reprise refusée.');setMessage(d.message);await load();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <section className="card my-6"><h3 className="text-2xl font-bold">Livraisons DayZ au redémarrage</h3><p className="my-3">Lance Redémarrer depuis Actions serveur pour traiter les commandes réservées. Un cycle terminé ne prouve pas l’apparition des objets : confirme les commandes après vérification en jeu.</p><a href="/api/restart-shop?template=1" className="underline block my-3">Télécharger le fichier Object Spawner vide pour l’installation</a><a href="/servers#server-actions" className="underline">Ouvrir Actions serveur</a><button disabled={busy} type="button" className="btn bg-white/10 ml-3" onClick={load}>Actualiser les lots</button>{rows.slice(-20).reverse().map(b=><div className="my-3 rounded-xl bg-black/30 p-4" key={b.id}><p className="break-all">Lot {b.id} — {labels[b.status]||'Opération en cours'}</p><p>{b.orderIds.length} commandes — serveur {b.serverId}</p>{b.error&&<p className="text-amber-300">{b.error}</p>}{b.status==='uncertain'&&<><label className="block mt-3">Compte rendu : objets présents ou absents, état du serveur<textarea className="input" value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/></label><button disabled={busy||note.trim().length<10} className="btn bg-white/10 mt-3" type="button" onClick={()=>recover(b)}>Vider le fichier du lot et débloquer la reprise</button><p className="text-white/70 mt-2">Cette action ne rembourse ni ne relivre automatiquement. Le staff traite ensuite chaque commande.</p></>}</div>)}{message&&<p role="status">{message}</p>}</section>;
}
