'use client';
import {useEffect,useState} from 'react';
import ModuleEditor from './ModuleEditor';
const fields=[{name:'level',label:'Niveau',type:'integer',required:true},{name:'xp',label:'XP requis',type:'integer',required:true},{name:'reward',label:'Récompense banque',type:'integer'},{name:'game',label:'Jeu (vide = tous)'},{name:'serverId',label:'ID exact du serveur (vide = tous)'},{name:'premium',label:'Piste premium',type:'boolean',defaultValue:false}];
const localDate=value=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export default function SeasonPassEditor(){
 const [seasons,setSeasons]=useState([]),[selected,setSelected]=useState(''),[form,setForm]=useState({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/battlepass?collection=seasons',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Chargement impossible.');setSeasons(d);}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function save(e,remove=false){e.preventDefault();setBusy(true);setMessage('');try{const body={...form,collection:'seasons'};if(!remove){body.startsAt=new Date(form.startsAt).toISOString();body.endsAt=new Date(form.endsAt).toISOString();}const r=await fetch('/api/battlepass',{method:remove?'DELETE':form.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Enregistrement impossible.');setForm({});await load();setMessage('Saisons enregistrées.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const season=seasons.find(s=>s.id===selected),locked=season&&Date.parse(season.startsAt)<=Date.now();
 return <><section className="card my-6 space-y-4"><h3 className="text-2xl font-black">Saisons</h3><p>Le début est inclus, la fin est exclue. Le changement de saison suit automatiquement ces dates. Les horaires ci-dessous utilisent le fuseau de votre appareil.</p><p>Configurez le modèle de niveaux avant de créer une saison : il est copié à sa création. Vous pouvez ensuite personnaliser une saison future. Les niveaux sont figés dès son début ; les anciennes progressions restent conservées. Les récompenses gratuites sont versées lors de la validation des quêtes. Les niveaux peuvent cibler un jeu ou un serveur. Le staff attribue les accès premium ci-dessous ; les niveaux acquis sont payés une seule fois. Les quêtes automatiques alimentent aussi le pass.</p>{message&&<p role="status">{message}</p>}
 <form onSubmit={save} className="grid gap-4 sm:grid-cols-3"><label>Nom<input className="input" required maxLength={100} value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label>{['startsAt','endsAt'].map((key,i)=><label key={key}>{i?'Fin':'Début'}<input type="datetime-local" className="input" required value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<button className="btn btn-primary" disabled={busy}>{form.id?'Modifier la saison':'Créer la saison'}</button>{form.id&&<><button type="button" className="btn" onClick={()=>setForm({})}>Annuler</button><button className="btn bg-red-700" disabled={busy} onClick={e=>save(e,true)}>Supprimer la saison future</button></>}</form>
 {seasons.map(s=><div key={s.id} className="rounded-xl bg-black/30 p-3"><b>{s.name}</b><p>{new Date(s.startsAt).toLocaleString('fr-FR')} → {new Date(s.endsAt).toLocaleString('fr-FR')} — {Date.now()<Date.parse(s.startsAt)?'À venir':Date.now()<Date.parse(s.endsAt)?'Active':'Terminée'}</p>{Date.now()<Date.parse(s.startsAt)&&<button className="btn" onClick={()=>setForm({...s,startsAt:localDate(s.startsAt),endsAt:localDate(s.endsAt)})}>Modifier les dates</button>}</div>)}
 <label className="block">Niveaux à afficher<select className="input" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Modèle pour les nouvelles saisons / pass historique</option>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
 {locked&&<div>{season.levels.map(l=><p key={l.id}>Niveau {l.level} — {l.xp} XP — {l.reward} banque — {l.premium?'Premium':'Gratuit'}</p>)}{!season.levels.length&&<p>Aucun niveau dans cette saison.</p>}</div>}</section>
 {!locked&&<ModuleEditor key={selected} endpoint={'/api/battlepass'+(selected?'?seasonId='+encodeURIComponent(selected):'')} title={season?'Niveaux de '+season.name:'Modèle de niveaux'} fields={fields}/>}<ModuleEditor key={'premium'+selected} endpoint={'/api/battlepass?collection=premium'+(selected?'&seasonId='+encodeURIComponent(selected):'')} listKey="premium" title="Accès à la piste premium" fields={[{name:'userId',label:'ID Discord du joueur',required:true}]}/></>;
}
