'use client';
import {useEffect,useState} from 'react';
import hosting from '../lib/hosting.cjs';
import games from '../lib/games.cjs';
export default function ServerActions(){
 const [servers,setServers]=useState([]),[serverId,setId]=useState(''),[command,setCommand]=useState(''),[message,setMessage]=useState(''),[jobs,setJobs]=useState([]),[busy,setBusy]=useState(false);
 const server=servers.find(s=>s.id===serverId),panel=hosting.panelUrl(server),nitrado=hosting.isNitrado(server)&&games.games[server?.game]?.hosting!==false&&!!(server?.nitradoServiceId||server?.nitradoId);
 const power=nitrado||!!(server?.apiType==='cmdhosting'&&server.panelConfigured&&server.panelServerId)||!!(server?.apiType==='pterodactyl'&&server.panelConfigured&&server.panelServerId);
 const rcon=!!server&&!!(games.games[server.game]?.rcon||(server.game==='arma'&&server.rconProtocol==='battleye'))&&!!(server.rconHost||server.rcon_host||server.host||server.ip)&&!!(server.rconPort||server.rcon_port||server.rcon||server.port)&&server.rconConfigured;
 async function load(){try{const r=await fetch('/api/servers',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Chargement impossible.');setServers(d.servers||[]);setId(old=>d.servers.some(s=>s.id===old)?old:d.servers[0]?.id||'');}catch(e){setMessage(e.message);}}
 useEffect(()=>{load();window.addEventListener('servers-updated',load);return()=>window.removeEventListener('servers-updated',load);},[]);
 async function results(){const r=await fetch('/api/rcon',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Résultats indisponibles.');setJobs(Array.isArray(d)?d:[]);}
 async function call(endpoint,body){setBusy(true);setMessage('');try{const r=await fetch(endpoint,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Action refusée.');setMessage(d.message||`Statut : ${d.status||'inconnu'} — joueurs : ${d.players??'indisponible'}`);if(['/api/rcon','/api/panel'].includes(endpoint))await results();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <section id="server-actions" className="card my-6 space-y-4"><h3 className="text-2xl font-black">Actions serveur</h3><label className="block">Serveur<select className="input" disabled={busy} value={serverId} onChange={e=>{setId(e.target.value);setMessage('');}}><option value="">Choisir un serveur</option>{servers.map(s=><option key={s.id} value={s.id}>{s.name} — {(s.provider==='other'&&s.providerName)||hosting.providers[s.provider]||s.providerName||(hosting.isNitrado(s)?'Nitrado':'Autre hébergeur')}</option>)}</select></label><button type="button" disabled={busy} className="btn bg-white/10" onClick={load}>Actualiser les serveurs</button>
 {panel&&<a className="btn btn-primary inline-block" href={panel} target="_blank" rel="noopener noreferrer">Ouvrir le panel hébergeur</a>}
 {power?<div className="flex flex-wrap gap-3"><button className="btn bg-white/10" disabled={busy} onClick={()=>call('/api/panel?serverId='+encodeURIComponent(serverId))}>Vérifier le statut</button>{[['start','Démarrer'],['stop','Arrêter'],['restart','Redémarrer']].map(([action,label])=><button className="btn bg-white/10" disabled={busy} key={action} onClick={()=>call('/api/panel',{serverId,action})}>{label}</button>)}</div>:server&&<p>Le démarrage et l’arrêt se font depuis le panel de cet hébergeur. Configure son lien dans Serveurs si nécessaire.</p>}
 <label className="block">Commande RCON<input className="input mt-2" value={command} onChange={e=>setCommand(e.target.value)}/></label>{server&&!rcon&&<p>Pour envoyer une commande, configure l’adresse, le port et le mot de passe RCON dans Serveurs. Le jeu et l’hébergeur doivent permettre cet accès.</p>}<button className="btn btn-primary" disabled={busy||!rcon||!command.trim()} onClick={()=>call('/api/rcon',{serverId,command})}>Envoyer</button><button className="btn bg-white/10" disabled={busy} onClick={()=>results().catch(e=>setMessage(e.message))}>Actualiser les résultats</button>{message&&<p role="status">{message}</p>}{jobs.map(j=><div key={j.id} className="rounded-xl bg-black/30 p-3"><b>{j.kind} — {j.status}</b><pre className="whitespace-pre-wrap text-sm">{j.result}</pre></div>)}
 </section>;
}
