'use client';
import {useEffect,useState} from 'react';
export default function SetupGuide(){
 const [servers,setServers]=useState(null),[error,setError]=useState('');
 async function load(){setError('');try{const r=await fetch('/api/servers',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Impossible de charger tes serveurs.');setServers(d.servers||[]);}catch(e){setError(e.message);}}
 useEffect(()=>{load();window.addEventListener('servers-updated',load);return()=>window.removeEventListener('servers-updated',load);},[]);
 const added=!!servers?.length,connected=servers?.some(s=>s.liveState?.status==='connected'||s.bridgeState?.status==='connected'||['online','running','started','api_reachable','rcon_reachable'].includes(s.monitorState?.status));
 const steps=[['Ajouter ton serveur','Choisis le jeu, le nom et l’hébergeur.','/servers#server-editor',added?'Serveur ajouté':'Commencer'],['Connecter ton hébergeur','Dans les réglages avancés du serveur, renseigne les accès disponibles.','/servers#server-editor','Configurer les accès'],['Tester la connexion','Vérifie le statut du panel, ou teste CFTools / BattleMetrics dans Administration connectée.','/servers#server-actions',connected?'Connexion observée':'Vérifier le statut'],['Choisir tes modules','Active les logs dans Serveurs, puis configure whitelist, boutique, quêtes et pass depuis leurs pages.','/#modules','Voir les modules']];
 return <section className="card mb-6" aria-label="Démarrage guidé"><h2 className="text-2xl font-black">Démarrer avec mon serveur</h2><p className="mt-2 mb-4 text-white/70">Suis ces quatre étapes. Tu peux revenir à tout moment pour modifier tes réglages.</p>{error&&<p role="status">{error} <button type="button" className="underline" onClick={load}>Réessayer</button></p>}<ol className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{steps.map(([title,description,href,label],i)=><li key={title} className="rounded-2xl bg-black/30 p-4"><h3 className="font-bold">{i+1}. {title}</h3><p className="text-white/70 my-3">{description}</p><a href={href} className="btn bg-white/10 inline-block">{label}</a>{i===2&&<a href="/integrations" className="block underline mt-3">Tester CFTools / BattleMetrics</a>}</li>)}</ol>{servers===null&&!error&&<p role="status" className="mt-3 text-white/60">Chargement de tes serveurs…</p>}</section>;
}
