'use client';
import {useState} from 'react';
import coords from '../lib/map-model.cjs';
export default function ShopPosition({item}){
 const [point,setPoint]=useState(null),[y,setY]=useState(''),[message,setMessage]=useState('');
 const map=item.positionMap,command=[point?.x,point?.z].every(Number.isFinite)&&y!==''&&Number.isFinite(Number(y))?`/shop buy id:${item.id} x:${point.x} z:${point.z} y:${Number(y)}`:'';
 function pick(e){const r=e.currentTarget.getBoundingClientRect(),p=coords.unproject(map,(e.clientX-r.left)/r.width*1000,(e.clientY-r.top)/r.height*1000);setPoint({x:Math.round(p.x),z:Math.round(p.y)});setMessage('');}
 return <details className="mt-4"><summary className="font-bold cursor-pointer">Choisir mon point de livraison {item.game==='ark'?'ARK':'DayZ'}</summary><p className="my-3 text-white/70">{item.game==='ark'?'Nécessite un adaptateur ARK installé qui remet les commandes après redémarrage.':'Commande réservée pour le prochain redémarrage lancé par le bot.'} Les objets apparaissent au sol ; cet emplacement ne sera pas privé aux autres joueurs.</p>{map?<><p>{map.name} — touche la carte pour choisir X / Z.</p><svg viewBox="0 0 1000 1000" role="img" aria-label={'Point de livraison sur '+map.name} className="w-full bg-black/30 rounded-2xl border border-white/30" onClick={pick}>{map.imageUrl&&<image href={map.imageUrl} width="1000" height="1000" preserveAspectRatio="none"/>}{[point?.x,point?.z].every(Number.isFinite)&&(()=>{const p=coords.project(map,point.x,point.z);return <circle cx={p.x} cy={p.y} r="18" fill="#facc15" stroke="black" strokeWidth="5"/>;})()}</svg><div className="grid gap-2 grid-cols-2 my-3">{['x','z'].map(k=><label key={k}>{k.toUpperCase()}<input className="input" type="number" step="1" value={point?.[k]??''} onChange={e=>{setPoint({...point,[k]:e.target.value===''?undefined:Number(e.target.value)});setMessage('');}}/></label>)}</div><label>Altitude Y exacte (mètres)<input className="input" type="number" step="any" min={item.game==='ark'?-10000000:-100} max={item.game==='ark'?10000000:3000} value={y} onChange={e=>setY(e.target.value)}/></label><p className="text-sm text-white/70 mt-2">Une carte 2D ne donne pas l’altitude. Demande la hauteur exacte au staff pour éviter un objet enterré ou suspendu.</p><button type="button" disabled={!command||![point?.x,point?.z].every(Number.isFinite)||point.x<map.xMin||point.x>map.xMax||point.z<map.yMin||point.z>map.yMax||Number(y)<(item.game==='ark'?-10000000:-100)||Number(y)>(item.game==='ark'?10000000:3000)} className="btn btn-primary mt-3" onClick={async()=>{try{await navigator.clipboard.writeText(command);setMessage('Commande copiée : colle-la dans le Discord du serveur pour acheter.');}catch{setMessage('Copie manuellement la commande affichée ci-dessous.');}}}>Copier la commande d’achat Discord</button>{command&&<code className="block break-all mt-3">{command}</code>}{message&&<p role="status" className="mt-2">{message}</p>}</>:<p className="my-3">Le staff doit publier une carte calibrée pour proposer le choix visuel. Tu peux acheter avec /shop buy en indiquant X, Z et l’altitude Y exacte.</p>}</details>;
}
