'use client';
import {useEffect,useRef,useState} from 'react';
import Shell from '../../components/Shell';
import AssistantChat from '../../components/AssistantChat';
import model from '../../lib/map-model.cjs';
import catalog from '../../lib/map-catalog.cjs';
import tiles from '../../lib/map-tiles.cjs';
import gameModel from '../../lib/games.cjs';
const colors={base:'#a78bfa',danger:'#f87171',loot:'#facc15',meeting:'#34d399',poi:'#60a5fa'};
const categories={base:'Base',danger:'Danger',loot:'Loot',meeting:'Rendez-vous',poi:'Point d’intérêt'};
const blank={name:'',serverId:'',imageUrl:'',xMin:0,xMax:100,yMin:0,yMax:100,flipY:true,public:false,publicPins:false};
function PublicFrame({children}){return <main className="min-h-screen p-5 lg:p-10 max-w-7xl mx-auto"><nav className="flex flex-wrap gap-4 mb-8"><a href="/public" className="font-bold">Extinction++ RSS</a><a href="https://discord.gg/t5dGcykTdE" target="_blank" rel="noopener noreferrer" className="btn btn-primary">Rejoindre notre Discord</a><a href="/help" className="btn bg-white/10">Aide gratuite</a><a href="/groups" className="btn bg-white/10">Groupes de joueurs</a><a href="/api/mod-auth/login" className="btn btn-primary">Administrer avec Discord</a><a href="/install" className="btn bg-white/10">Installer l’application</a></nav>{children}</main>;}
export default function Maps({readOnly=false,groupId=null}){
  const Frame=readOnly||groupId?PublicFrame:Shell;
  const [data,setData]=useState({maps:[],pins:[],servers:[]}),[mapId,setMapId]=useState(''),[config,setConfig]=useState(blank),[showConfig,setShowConfig]=useState(false),[pin,setPin]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState({x:0,y:0,size:1000}),[filter,setFilter]=useState('all'),[imageFailed,setImageFailed]=useState(false),[tileFailed,setTileFailed]=useState(false),[gameFilter,setGameFilter]=useState('all');
  const svg=useRef(),drag=useRef();const map=data.maps.find(m=>m.id===mapId);
  async function load(){const r=await fetch(groupId?`/api/groups/${groupId}/maps`:readOnly?'/api/public/maps':'/api/maps',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setMapId(previous=>d.maps.some(m=>m.id===previous)?previous:d.maps[0]?.id||'');}
  useEffect(()=>{load().catch(e=>setMessage(e.message));if(!groupId)return;const timer=setInterval(()=>{if(!document.hidden)load().catch(e=>setMessage(e.message));},15000);return ()=>clearInterval(timer);},[groupId]);
  useEffect(()=>{setView({x:0,y:0,size:1000});setPin(null);setImageFailed(false);setTileFailed(false);},[mapId]);
  async function send(endpoint,body,method){setBusy(true);setMessage('');try{const r=await fetch(groupId?`/api/groups/${groupId}/maps`:endpoint,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error);await load();setMessage('Enregistré.');setPin(null);setShowConfig(false);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
  function point(event){const p=svg.current.createSVGPoint();p.x=event.clientX;p.y=event.clientY;return p.matrixTransform(svg.current.getScreenCTM().inverse());}
  function zoom(factor){setView(v=>{const size=Math.max(50,Math.min(1000,v.size*factor));return {x:Math.max(0,Math.min(1000-size,v.x+(v.size-size)/2)),y:Math.max(0,Math.min(1000-size,v.y+(v.size-size)/2)),size};});}
  function down(e){if(e.button!==0)return;drag.current={x:e.clientX,y:e.clientY,start:view,moved:false};e.currentTarget.setPointerCapture(e.pointerId);}
  function move(e){const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>5)d.moved=true;const rect=svg.current.getBoundingClientRect(),scale=d.start.size/Math.min(rect.width,rect.height);setView({...d.start,x:Math.max(0,Math.min(1000-d.start.size,d.start.x-dx*scale)),y:Math.max(0,Math.min(1000-d.start.size,d.start.y-dy*scale))});}
  function up(e){const d=drag.current;drag.current=null;if(!d||d.moved||!map||readOnly)return;const p=point(e);if(p.x<0||p.y<0||p.x>1000||p.y>1000)return;const coords=model.unproject(map,p.x,p.y);setPin({mapId:map.id,name:'',category:'poi',description:'',x:Number(coords.x.toFixed(2)),y:Number(coords.y.toFixed(2))});}
  const shownMaps=data.maps.filter(m=>gameFilter==='all'||m.game===gameFilter);
  const visibleTiles=map?tiles.visibleTiles(map,view):[];
  const pins=data.pins.filter(p=>p.mapId===mapId&&(filter==='all'||p.category===filter));
  return <Frame><h1 className="text-4xl font-black mb-5">Cartes interactives</h1><p className="text-white/70 mb-5">DayZ, ARK, Arma Reforger, Conan, Palworld, 7 Days to Die, Aniimo et cartes modées. Déplace la carte, utilise + / − pour zoomer {readOnly?'Les cartes publiées sont accessibles sans compte.':'Touche la carte pour placer un marqueur.'}</p><AssistantChat compact/>{message&&<p role="status" className="card mb-5">{message}</p>}
    <div className="flex flex-wrap gap-3 mb-5"><select aria-label="Filtrer par jeu" className="input" value={gameFilter} onChange={e=>{const game=e.target.value;setGameFilter(game);setMapId(data.maps.find(m=>game==='all'||m.game===game)?.id||'');}}><option value="all">Tous les jeux</option>{[...new Set(data.maps.map(m=>m.game))].map(game=><option key={game} value={game}>{gameModel.games[game]?.name||game}</option>)}</select><select aria-label="Carte active" className="input flex-1" value={mapId} onChange={e=>setMapId(e.target.value)}><option value="">Choisir une carte</option>{shownMaps.map(m=><option key={m.id} value={m.id}>{m.name}{readOnly||groupId?` — ${gameModel.games[m.game]?.name||m.game}${m.modded?' (mod)':''}`:` — ${data.servers.find(s=>s.id===m.serverId)?.name||m.game}`}</option>)}</select>{!readOnly&&!groupId&&<button className="btn btn-primary" onClick={()=>{setConfig({...blank,serverId:data.servers[0]?.id||''});setShowConfig(true);}}>Ajouter une carte</button>}{!readOnly&&!groupId&&map&&<button className="btn bg-white/10" onClick={()=>{setConfig(map);setShowConfig(true);}}>Configurer cette carte</button>}<button className="btn bg-white/10" onClick={()=>load().catch(e=>setMessage(e.message))}>Actualiser</button></div>
    {showConfig&&<form className="card mb-5 grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();send('/api/maps',config,config.id?'PATCH':'POST');}}><h2 className="text-2xl font-black sm:col-span-2">Carte officielle ou modée</h2><label>Serveur<select className="input" value={config.serverId} required onChange={e=>setConfig({...config,serverId:e.target.value})}><option value="">Choisir</option>{data.servers.map(s=><option key={s.id} value={s.id}>{s.name} — {s.game}</option>)}</select></label><label>Nom de la carte<input list="map-suggestions" className="input" value={config.name} onChange={e=>setConfig({...config,name:e.target.value})}/></label><datalist id="map-suggestions">{catalog.suggestions(data.servers.find(s=>s.id===config.serverId)?.game,data.servers,data.maps).map(name=><option key={name} value={name}/>)}</datalist><label className="sm:col-span-2">Fond de carte (lien HTTPS d’une image utilisable)<input type="url" className="input" value={config.imageUrl} onChange={e=>setConfig({...config,imageUrl:e.target.value})}/></label><p className="sm:col-span-2 text-white/60">Utilise les limites réelles du terrain pour X / Z. Pour ARK, tu peux utiliser longitude / latitude de 0 à 100. Les fonds et coordonnées des cartes modées doivent être fournis par leur auteur ou par ton serveur.</p>{[['xMin','X minimum'],['xMax','X maximum'],['yMin','Z / latitude minimum'],['yMax','Z / latitude maximum']].map(([name,label])=><label key={name}>{label}<input required type="number" step="any" className="input" value={config[name]} onChange={e=>setConfig({...config,[name]:Number(e.target.value)})}/></label>)}<label className="sm:col-span-2"><input type="checkbox" checked={config.flipY} onChange={e=>setConfig({...config,flipY:e.target.checked})}/> Les valeurs Z / latitude augmentent vers le haut de l’image</label><label className="sm:col-span-2"><input type="checkbox" checked={config.public===true} onChange={e=>setConfig({...config,public:e.target.checked})}/> Publier cette carte sans connexion</label><label className="sm:col-span-2"><input type="checkbox" disabled={!config.public} checked={config.publicPins===true} onChange={e=>setConfig({...config,publicPins:e.target.checked})}/> Publier aussi tous ses marqueurs et descriptions (y compris les bases)</label><button disabled={busy} className="btn btn-primary">Enregistrer</button><button type="button" className="btn bg-white/10" onClick={()=>setShowConfig(false)}>Annuler</button>{config.id&&<button type="button" className="btn bg-red-700" disabled={busy} onClick={()=>send('/api/maps',config,'DELETE')}>Supprimer cette carte et ses marqueurs</button>}</form>}
    {map?<><div className="flex gap-3 mb-3"><button aria-label="Zoom avant" className="btn bg-white/10" onClick={()=>zoom(.7)}>+</button><button aria-label="Zoom arrière" className="btn bg-white/10" onClick={()=>zoom(1.4)}>−</button><button className="btn bg-white/10" onClick={()=>setView({x:0,y:0,size:1000})}>Vue entière</button><select aria-label="Catégorie de marqueurs" className="input" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tous les marqueurs</option>{Object.entries(categories).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></div>
      {(!map.imageUrl||imageFailed||tileFailed)&&<p className="mb-3 text-amber-300">{imageFailed||tileFailed?'Une partie du fond ne se charge pas. La source externe est peut-être indisponible.':'Fond de carte à configurer. La grille permet de préparer les marqueurs.'}</p>}
      <svg ref={svg} role="img" aria-label={'Carte de '+map.name} viewBox={`${view.x} ${view.y} ${view.size} ${view.size}`} className="w-full border border-white/20 rounded-2xl bg-[#132230]" style={{height:'min(70vh,800px)',touchAction:'none'}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{drag.current=null}} onWheel={e=>zoom(e.deltaY>0?1.15:.85)}><defs><pattern id="map-grid" width="100" height="100" patternUnits="userSpaceOnUse"><path d="M 100 0 L 0 0 0 100" fill="none" stroke="#ffffff25" strokeWidth="1"/></pattern></defs><rect width="1000" height="1000" fill="url(#map-grid)"/>{!map.tileTemplate&&map.imageUrl&&!imageFailed&&<image href={map.imageUrl} width="1000" height="1000" preserveAspectRatio="none" onError={()=>setImageFailed(true)}/>} {visibleTiles.map(tile=><image key={tile.id} href={tile.url} x={tile.x} y={tile.y} width={tile.width} height={tile.width} preserveAspectRatio="none" onError={()=>setTileFailed(true)}/>)}{map.overlayUrl&&<image href={map.overlayUrl} width="1000" height="1000" preserveAspectRatio="none" style={{mixBlendMode:'screen'}} onError={()=>setTileFailed(true)}/>} {pins.map(p=>{const pos=model.project(map,p.x,p.y);return <g key={p.id} onPointerDown={e=>e.stopPropagation()} onPointerUp={e=>{e.stopPropagation();setPin(p)}} style={{cursor:'pointer'}}><circle cx={pos.x} cy={pos.y} r={Math.max(4,view.size/65)} fill={colors[p.category]} stroke="#111" strokeWidth={view.size/500}/><title>{p.name} — {p.x}, {p.y}</title><text x={pos.x+view.size/50} y={pos.y} fill="white" stroke="#111" strokeWidth={view.size/700} paintOrder="stroke" fontSize={view.size/45}>{p.name}</text></g>})}</svg><p className="text-sm text-white/60 mt-2">{map.name} — X : {map.xMin} à {map.xMax} ; Y / Z : {map.yMin} à {map.yMax}. {groupId?'Marqueurs privés de ton groupe.':readOnly?'Consultation publique.':'Marqueurs partagés avec les fondateurs de ce Discord.'}</p>{map.coordinateLabel&&<p className="text-sm text-white/60 mt-2">{map.coordinateLabel}</p>}{map.sourceUrl&&<p className="text-sm text-white/60 mt-2">{map.attribution} <a className="underline" href={map.sourceUrl} target="_blank" rel="noreferrer">Voir la source</a></p>}</>:<div className="card">{readOnly||groupId?'Aucune carte publiée pour le moment. Un administrateur peut publier une carte depuis Cartes interactives.':'Aucune carte configurée. Ajoute ton serveur dans Serveurs, puis sa carte ici.'}</div>}
    {pin&&!readOnly&&<form className="card mt-5 grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();send('/api/map-pins',pin,pin.id?'PATCH':'POST');}}><h2 className="text-2xl font-black sm:col-span-2">{pin.id?'Modifier le marqueur':'Nouveau marqueur'}</h2><label>Nom<input required maxLength={160} className="input" value={pin.name} onChange={e=>setPin({...pin,name:e.target.value})}/></label><label>Catégorie<select className="input" value={pin.category} onChange={e=>setPin({...pin,category:e.target.value})}>{Object.entries(categories).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>{[['x','X / longitude'],['y',map?.coordinateLabel?'Y (coordonnée visuelle)':'Z / latitude']].map(([key,label])=><label key={key}>{label}<input type="number" step="any" className="input" value={pin[key]} onChange={e=>setPin({...pin,[key]:Number(e.target.value)})}/></label>)}<label className="sm:col-span-2">Description<textarea className="input" value={pin.description} onChange={e=>setPin({...pin,description:e.target.value})}/></label><button className="btn btn-primary" disabled={busy}>Enregistrer le marqueur</button><button className="btn bg-white/10" type="button" onClick={()=>setPin(null)}>Fermer</button>{pin.id&&<button className="btn bg-red-700" type="button" disabled={busy} onClick={()=>send('/api/map-pins',pin,'DELETE')}>Supprimer</button>}</form>}
    {pin&&readOnly&&<div className="card mt-5"><h2 className="text-xl font-bold">{pin.name}</h2><p>{pin.description}</p><p>{pin.x}, {pin.y}</p><button className="btn bg-white/10" onClick={()=>setPin(null)}>Fermer</button></div>}
    {pins.length>0&&<div className="card mt-5 space-y-2"><h2 className="text-xl font-bold">Marqueurs</h2>{pins.map(p=><button key={p.id} className="block text-left" onClick={()=>{setPin(p);const pos=model.project(map,p.x,p.y);setView({x:Math.max(0,Math.min(750,pos.x-125)),y:Math.max(0,Math.min(750,pos.y-125)),size:250});}}>{p.name} — {categories[p.category]} — {p.x}, {p.y}</button>)}</div>}
  </Frame>;
}
