import Shell from '../../components/Shell';
import ModuleEditor from '../../components/ModuleEditor';
import {readPageDb} from '../../lib/db';
export default async function Operations(){const db=await readPageDb();const players=db.livePlayers||[];
return <Shell><h2 className="mb-6 text-4xl font-black">Primes, factions et automatisations</h2>
<div className="card mb-6 space-y-3"><p>Tous les jeux proposés peuvent utiliser les primes. Sans événement de jeu importé, le staff valide une preuve et un bénéficiaire dont l’identité a été vérifiée. Les primes sont prélevées dans la banque du commanditaire à leur création, puis versées au tueur lié à Discord lorsque son kill apparaît dans les logs. À expiration ou annulation, le commanditaire est remboursé. Pas de paiement pour un suicide, un compte identique ou un membre de la même faction.</p><p>Vérifie les identités avant de confirmer une liaison Discord ↔ UID. Les récompenses concernent les événements importés après activation. Les tâches serveur utilisent Nitrado ou un panel Pterodactyl configuré ; les messages en jeu utilisent un RCON compatible.</p><p>Les zones peuvent écrire une sanction dans le fichier ban.txt configuré. La prise en compte par le jeu doit être vérifiée et peut nécessiter une recharge. Une opération interrompue est suspendue et affichée comme non confirmée.</p><p>Les dates des tâches acceptent un fuseau explicite : 2026-10-05T02:00:00+02:00.</p></div>
<div className="card mb-6 overflow-x-auto"><h3 className="text-2xl font-black mb-3">Joueurs observés dans les logs</h3><table className="w-full text-left"><thead><tr><th>Joueur</th><th>UID du jeu</th><th>Serveur ID</th><th>Kills</th><th>Morts</th><th>Position connue</th></tr></thead><tbody>{players.map(p=><tr key={p.id}><td>{p.name}</td><td className="break-all">{p.uid}</td><td>{p.serverId}</td><td>{p.kills||0}</td><td>{p.deaths||0}</td><td>{p.x!==undefined?`${p.x}, ${p.z}`:'—'}<br/>{p.lastSeen}</td></tr>)}</tbody></table>{!players.length&&<p>Aucun joueur observé. Active les logs dans Serveurs.</p>}</div>
<ModuleEditor title="Liaisons joueurs (validation par le staff)" endpoint="/api/operations?collection=playerLinks" fields={[{name:'serverId',label:'ID exact du serveur',required:true},{name:'userId',label:'ID Discord du joueur',required:true},{name:'uid',label:'UID du jeu',required:true},{name:'name',label:'Pseudo'},{name:'verified',label:'Identité vérifiée par le staff',type:'boolean'}]}/>
<ModuleEditor title="Primes" endpoint="/api/operations?collection=bounties" allowDelete={false} fields={[{name:'serverId',label:'ID exact du serveur',required:true},{name:'creatorId',label:'ID Discord du commanditaire',required:true},{name:'targetUid',label:'UID de la cible',required:true},{name:'targetName',label:'Pseudo de la cible'},{name:'amount',label:'Montant en monnaie virtuelle',type:'integer',required:true},{name:'hours',label:'Durée en heures (168 par défaut)',type:'integer'},{name:'status',label:'Décision pour une prime existante',options:{cancelled:'Annuler et rembourser',claimed:'Valider la prime avec preuve (staff)'}},{name:'claimedBy',label:'ID Discord du bénéficiaire vérifié'},{name:'evidence',label:'Lien de preuve ou motif de validation du staff'}]}/>
<ModuleEditor title="Factions" endpoint="/api/operations?collection=factions" fields={[{name:'name',label:'Nom',required:true},{name:'serverId',label:'ID exact du serveur',required:true},{name:'leaderId',label:'ID Discord du chef',required:true},{name:'members',label:'IDs Discord des membres, séparés par des virgules',type:'strings'}]}/>
<ModuleEditor title="Récompenses automatiques" endpoint="/api/operations?collection=eventRules" fields={[{name:'name',label:'Nom',required:true},{name:'serverId',label:'ID exact du serveur',required:true},{name:'type',label:'Événement',options:{kill:'Kill'},required:true},{name:'amount',label:'Récompense',type:'integer',required:true},{name:'cooldownSeconds',label:'Délai entre récompenses en secondes (300 par défaut)',type:'integer'},{name:'requireLinkedVictim',label:'Exiger une victime liée à Discord',type:'boolean',defaultValue:true},{name:'enabled',label:'Activée',type:'boolean'}]}/>
<ModuleEditor title="Tâches programmées" endpoint="/api/operations?collection=scheduledTasks" fields={[{name:'name',label:'Nom',required:true},{name:'serverId',label:'ID exact du serveur',required:true},{name:'action',label:'Action',required:true,options:{restart:'Redémarrer (API du panel)',start:'Démarrer (API du panel)',stop:'Arrêter (API du panel)',message:'Message en jeu (RCON)'}},{name:'message',label:'Message, si cette action est choisie'},{name:'nextRunAt',label:'Prochaine exécution (date ISO avec fuseau)',required:true},{name:'intervalSeconds',label:'Répétition en secondes (0 = une seule fois)',type:'integer'},{name:'enabled',label:'Activée',type:'boolean'}]}/>
<ModuleEditor title="Sanctions : ajout au fichier ban.txt" endpoint="/api/operations?collection=gameActions" allowDelete={false} fields={[{name:'serverId',label:'ID exact du serveur',required:true},{name:'playerUid',label:'UID DayZ PC'},{name:'playerName',label:'Gamertag console'},{name:'reason',label:'Motif'}]}/>
</Shell>}
