const fs=require('node:fs/promises');
const path=require('node:path');
const {client}=require('../../shared/bridge-client.cjs');
const safeId=id=>typeof id==='string'&&/^[A-Za-z0-9_-]{1,128}$/.test(id);
async function json(file){const s=await fs.lstat(file);if(!s.isFile()||s.isSymbolicLink()||s.size>65536)throw new Error('Invalid local bridge file.');return JSON.parse(await fs.readFile(file,'utf8'));}
async function atomic(file,body){const temporary=file+'.'+process.pid+'.tmp';await fs.writeFile(temporary,JSON.stringify(body),{mode:0o600});await fs.rename(temporary,file);}
async function tick({root,remote,now=Date.now()}){const dirs=['events','delivery_requests','delivery_results','agent_ledger'];for(const dir of dirs)await fs.mkdir(path.join(root,dir),{recursive:true,mode:0o700});let alive=false,kits=false;
 try{const file=path.join(root,'alive.json'),heartbeat=await json(file),stat=await fs.stat(file);alive=heartbeat.protocol===1&&heartbeat.delivery===true&&stat.mtimeMs>=now-20000&&stat.mtimeMs<=now+5000;kits=alive&&heartbeat.kits===true;}catch{}
 const events=[];for(const name of (await fs.readdir(path.join(root,'events'))).filter(n=>n.endsWith('.json')).sort().slice(0,50)){const id=name.slice(0,-5);if(!safeId(id))continue;const file=path.join(root,'events',name);try{await fs.access(file+'.ready');const event=await json(file);if(event.id!==id)continue;require('../../dashboard/lib/game-bridge.cjs').event(event);events.push({file,event});}catch{}}
 // Feed positions only while the game process is alive. Old kill IDs can be retried safely.
 const imported=events.filter(e=>alive||e.event.type!=='position');await remote.events(imported.map(e=>e.event),{delivery:alive,kits});for(const e of events){if(imported.includes(e)||e.event.type==='position'){await fs.rm(e.file,{force:true});await fs.rm(e.file+'.ready',{force:true});}}
 for(const name of (await fs.readdir(path.join(root,'delivery_results'))).filter(n=>n.endsWith('.json')).slice(0,20)){const id=name.slice(0,-5);if(!safeId(id))continue;const ledger=path.join(root,'agent_ledger',id+'.json');try{const known=await json(ledger),result=await json(path.join(root,'delivery_results',name));if(known.id!==id||result.id!==id||!['delivered','delivery_uncertain'].includes(result.status))continue;await remote.ack(id,result.status,String(result.result||'').slice(0,500));await atomic(ledger,{...known,acknowledged:true,status:result.status});await fs.rm(path.join(root,'delivery_results',name),{force:true});}catch{}}
 // Only advertise native delivery after observing a fresh heartbeat from the actual mod.
 if(!alive)return {alive:false,events:imported.length};
 const {delivery}=await remote.claim();if(delivery){const contents=delivery.items||[{className:delivery.className,quantity:delivery.quantity}];if(!Array.isArray(contents)||!contents.length||contents.length>20||contents.some(v=>!/^[A-Za-z0-9_]{1,100}$/.test(v.className||'')||!Number.isSafeInteger(v.quantity)||v.quantity<1||v.quantity>100)||contents.reduce((n,v)=>n+v.quantity,0)>100)throw new Error('Invalid native kit.');delivery.items=contents;if(!safeId(delivery.id)||!delivery.playerUid||!/^[A-Za-z0-9_]{1,100}$/.test(delivery.className||'')||!Number.isSafeInteger(delivery.quantity)||delivery.quantity<1||delivery.quantity>100)throw new Error('Invalid native delivery.');const ledger=path.join(root,'agent_ledger',delivery.id+'.json');let previous;try{previous=await json(ledger);}catch(e){if(e.code!=='ENOENT')throw e;}if(previous){await remote.ack(delivery.id,'delivery_uncertain','Delivery already recorded locally; manual review required.');}else{await atomic(ledger,delivery);await atomic(path.join(root,'delivery_requests',delivery.id+'.json'),delivery);}}
 return {alive:true,events:imported.length};}
async function main(){const root=path.resolve(process.env.EXTINCTION_DAYZ_PROFILE||''),url=process.env.EXTINCTION_DASHBOARD_URL,guildId=process.env.EXTINCTION_GUILD_ID,serverId=process.env.EXTINCTION_SERVER_ID,secret=process.env.EXTINCTION_BRIDGE_SECRET;if(!process.env.EXTINCTION_DAYZ_PROFILE||!url||!guildId||!serverId||!secret)throw new Error('Set profile directory, dashboard URL, guild ID, server ID and bridge secret.');await fs.mkdir(root,{recursive:true,mode:0o700});const lock=path.join(root,'.agent.lock');const handle=await fs.open(lock,'wx',0o600);await handle.writeFile(String(process.pid));let stopped=false;const stop=()=>{stopped=true;};process.on('SIGINT',stop);process.on('SIGTERM',stop);const remote=client({url,guildId,serverId,secret});try{while(!stopped){try{await tick({root,remote});}catch{console.error('DayZ companion: connection or local queue unavailable; will retry.');}await new Promise(resolve=>setTimeout(resolve,5000));}}finally{await handle.close();await fs.rm(lock,{force:true});}}
if(require.main===module)main().catch(()=>{console.error('DayZ companion could not start. Check configuration and agent lock.');process.exitCode=1;});
module.exports={tick,json,atomic,safeId};
